insert into promociones (promocion,descuento)
values ('2x1',0.5)
insert into promociones (promocion,descuento)
values ('Descuento a jubilados',0.3)
insert into promociones (promocion,descuento)
values ('Descuento a estudiantes',0.2)
insert into promociones (promocion,descuento)
values ('Descuento día miercoles',0.4)