use cine

insert into butacas (cod_butaca,id_sala)
values('A1',1)
insert into butacas (cod_butaca,id_sala)
values('A2',1)
insert into butacas (cod_butaca,id_sala)
values('A3',1)
insert into butacas (cod_butaca,id_sala)
values('A4',1)
insert into butacas (cod_butaca,id_sala)
values('A5',1)
insert into butacas (cod_butaca,id_sala)
values('A6',1)
insert into butacas (cod_butaca,id_sala)
values('A7',1)
insert into butacas (cod_butaca,id_sala)
values('A8',1)
insert into butacas (cod_butaca,id_sala)
values('A9',1)
insert into butacas (cod_butaca,id_sala)
values('A10',1)

insert into butacas (cod_butaca,id_sala)
values('B1',1)
insert into butacas (cod_butaca,id_sala)
values('B2',1)
insert into butacas (cod_butaca,id_sala)
values('B3',1)
insert into butacas (cod_butaca,id_sala)
values('B4',1)
insert into butacas (cod_butaca,id_sala)
values('B5',1)
insert into butacas (cod_butaca,id_sala)
values('B6',1)
insert into butacas (cod_butaca,id_sala)
values('B7',1)
insert into butacas (cod_butaca,id_sala)
values('B8',1)
insert into butacas (cod_butaca,id_sala)
values('B9',1)
insert into butacas (cod_butaca,id_sala)
values('B10',1)

insert into butacas (cod_butaca,id_sala)
values('C1',1)
insert into butacas (cod_butaca,id_sala)
values('C2',1)
insert into butacas (cod_butaca,id_sala)
values('C3',1)
insert into butacas (cod_butaca,id_sala)
values('C4',1)
insert into butacas (cod_butaca,id_sala)
values('C5',1)
insert into butacas (cod_butaca,id_sala)
values('C6',1)
insert into butacas (cod_butaca,id_sala)
values('C7',1)
insert into butacas (cod_butaca,id_sala)
values('C8',1)
insert into butacas (cod_butaca,id_sala)
values('C9',1)
insert into butacas (cod_butaca,id_sala)
values('C10',1)

insert into butacas (cod_butaca,id_sala)
values('D1',1)
insert into butacas (cod_butaca,id_sala)
values('D2',1)
insert into butacas (cod_butaca,id_sala)
values('D3',1)
insert into butacas (cod_butaca,id_sala)
values('D4',1)
insert into butacas (cod_butaca,id_sala)
values('D5',1)
insert into butacas (cod_butaca,id_sala)
values('D6',1)
insert into butacas (cod_butaca,id_sala)
values('D7',1)
insert into butacas (cod_butaca,id_sala)
values('D8',1)
insert into butacas (cod_butaca,id_sala)
values('D9',1)
insert into butacas (cod_butaca,id_sala)
values('D10',1)

insert into butacas (cod_butaca,id_sala)
values('E1',1)
insert into butacas (cod_butaca,id_sala)
values('E2',1)
insert into butacas (cod_butaca,id_sala)
values('E3',1)
insert into butacas (cod_butaca,id_sala)
values('E4',1)
insert into butacas (cod_butaca,id_sala)
values('E5',1)
insert into butacas (cod_butaca,id_sala)
values('E6',1)
insert into butacas (cod_butaca,id_sala)
values('E7',1)
insert into butacas (cod_butaca,id_sala)
values('E8',1)
insert into butacas (cod_butaca,id_sala)
values('E9',1)
insert into butacas (cod_butaca,id_sala)
values('E10',1)

insert into butacas (cod_butaca,id_sala)
values('F1',1)
insert into butacas (cod_butaca,id_sala)
values('F2',1)
insert into butacas (cod_butaca,id_sala)
values('F3',1)
insert into butacas (cod_butaca,id_sala)
values('F4',1)
insert into butacas (cod_butaca,id_sala)
values('F5',1)
insert into butacas (cod_butaca,id_sala)
values('F6',1)
insert into butacas (cod_butaca,id_sala)
values('F7',1)
insert into butacas (cod_butaca,id_sala)
values('F8',1)
insert into butacas (cod_butaca,id_sala)
values('F9',1)
insert into butacas (cod_butaca,id_sala)
values('F10',1)

insert into butacas (cod_butaca,id_sala)
values('G1',1)
insert into butacas (cod_butaca,id_sala)
values('G2',1)
insert into butacas (cod_butaca,id_sala)
values('G3',1)
insert into butacas (cod_butaca,id_sala)
values('G4',1)
insert into butacas (cod_butaca,id_sala)
values('G5',1)
insert into butacas (cod_butaca,id_sala)
values('G6',1)
insert into butacas (cod_butaca,id_sala)
values('G7',1)
insert into butacas (cod_butaca,id_sala)
values('G8',1)
insert into butacas (cod_butaca,id_sala)
values('G9',1)
insert into butacas (cod_butaca,id_sala)
values('G10',1)

insert into butacas (cod_butaca,id_sala)
values('H1',1)
insert into butacas (cod_butaca,id_sala)
values('H2',1)
insert into butacas (cod_butaca,id_sala)
values('H3',1)
insert into butacas (cod_butaca,id_sala)
values('H4',1)
insert into butacas (cod_butaca,id_sala)
values('H5',1)
insert into butacas (cod_butaca,id_sala)
values('H6',1)
insert into butacas (cod_butaca,id_sala)
values('H7',1)
insert into butacas (cod_butaca,id_sala)
values('H8',1)
insert into butacas (cod_butaca,id_sala)
values('H9',1)
insert into butacas (cod_butaca,id_sala)
values('H10',1)

insert into butacas (cod_butaca,id_sala)
values('I1',1)
insert into butacas (cod_butaca,id_sala)
values('I2',1)
insert into butacas (cod_butaca,id_sala)
values('I3',1)
insert into butacas (cod_butaca,id_sala)
values('I4',1)
insert into butacas (cod_butaca,id_sala)
values('I5',1)
insert into butacas (cod_butaca,id_sala)
values('I6',1)
insert into butacas (cod_butaca,id_sala)
values('I7',1)
insert into butacas (cod_butaca,id_sala)
values('I8',1)
insert into butacas (cod_butaca,id_sala)
values('I9',1)
insert into butacas (cod_butaca,id_sala)
values('I10',1)

insert into butacas (cod_butaca,id_sala)
values('J1',1)
insert into butacas (cod_butaca,id_sala)
values('J2',1)
insert into butacas (cod_butaca,id_sala)
values('J3',1)
insert into butacas (cod_butaca,id_sala)
values('J4',1)
insert into butacas (cod_butaca,id_sala)
values('J5',1)
insert into butacas (cod_butaca,id_sala)
values('J6',1)
insert into butacas (cod_butaca,id_sala)
values('J7',1)
insert into butacas (cod_butaca,id_sala)
values('J8',1)
insert into butacas (cod_butaca,id_sala)
values('J9',1)
insert into butacas (cod_butaca,id_sala)
values('J10',1)



insert into butacas (cod_butaca,id_sala)
values('A1',2)
insert into butacas (cod_butaca,id_sala)
values('A2',2)
insert into butacas (cod_butaca,id_sala)
values('A3',2)
insert into butacas (cod_butaca,id_sala)
values('A4',2)
insert into butacas (cod_butaca,id_sala)
values('A5',2)
insert into butacas (cod_butaca,id_sala)
values('A6',2)
insert into butacas (cod_butaca,id_sala)
values('A7',2)
insert into butacas (cod_butaca,id_sala)
values('A8',2)
insert into butacas (cod_butaca,id_sala)
values('A9',2)
insert into butacas (cod_butaca,id_sala)
values('A10',2)

insert into butacas (cod_butaca,id_sala)
values('B1',2)
insert into butacas (cod_butaca,id_sala)
values('B2',2)
insert into butacas (cod_butaca,id_sala)
values('B3',2)
insert into butacas (cod_butaca,id_sala)
values('B4',2)
insert into butacas (cod_butaca,id_sala)
values('B5',2)
insert into butacas (cod_butaca,id_sala)
values('B6',2)
insert into butacas (cod_butaca,id_sala)
values('B7',2)
insert into butacas (cod_butaca,id_sala)
values('B8',2)
insert into butacas (cod_butaca,id_sala)
values('B9',2)
insert into butacas (cod_butaca,id_sala)
values('B10',2)

insert into butacas (cod_butaca,id_sala)
values('C1',2)
insert into butacas (cod_butaca,id_sala)
values('C2',2)
insert into butacas (cod_butaca,id_sala)
values('C3',2)
insert into butacas (cod_butaca,id_sala)
values('C4',2)
insert into butacas (cod_butaca,id_sala)
values('C5',2)
insert into butacas (cod_butaca,id_sala)
values('C6',2)
insert into butacas (cod_butaca,id_sala)
values('C7',2)
insert into butacas (cod_butaca,id_sala)
values('C8',2)
insert into butacas (cod_butaca,id_sala)
values('C9',2)
insert into butacas (cod_butaca,id_sala)
values('C10',2)

insert into butacas (cod_butaca,id_sala)
values('D1',2)
insert into butacas (cod_butaca,id_sala)
values('D2',2)
insert into butacas (cod_butaca,id_sala)
values('D3',2)
insert into butacas (cod_butaca,id_sala)
values('D4',2)
insert into butacas (cod_butaca,id_sala)
values('D5',2)
insert into butacas (cod_butaca,id_sala)
values('D6',2)
insert into butacas (cod_butaca,id_sala)
values('D7',2)
insert into butacas (cod_butaca,id_sala)
values('D8',2)
insert into butacas (cod_butaca,id_sala)
values('D9',2)
insert into butacas (cod_butaca,id_sala)
values('D10',2)

insert into butacas (cod_butaca,id_sala)
values('E1',2)
insert into butacas (cod_butaca,id_sala)
values('E2',2)
insert into butacas (cod_butaca,id_sala)
values('E3',2)
insert into butacas (cod_butaca,id_sala)
values('E4',2)
insert into butacas (cod_butaca,id_sala)
values('E5',2)
insert into butacas (cod_butaca,id_sala)
values('E6',2)
insert into butacas (cod_butaca,id_sala)
values('E7',2)
insert into butacas (cod_butaca,id_sala)
values('E8',2)
insert into butacas (cod_butaca,id_sala)
values('E9',2)
insert into butacas (cod_butaca,id_sala)
values('E10',2)

insert into butacas (cod_butaca,id_sala)
values('F1',2)
insert into butacas (cod_butaca,id_sala)
values('F2',2)
insert into butacas (cod_butaca,id_sala)
values('F3',2)
insert into butacas (cod_butaca,id_sala)
values('F4',2)
insert into butacas (cod_butaca,id_sala)
values('F5',2)
insert into butacas (cod_butaca,id_sala)
values('F6',2)
insert into butacas (cod_butaca,id_sala)
values('F7',2)
insert into butacas (cod_butaca,id_sala)
values('F8',2)
insert into butacas (cod_butaca,id_sala)
values('F9',2)
insert into butacas (cod_butaca,id_sala)
values('F10',2)

insert into butacas (cod_butaca,id_sala)
values('G1',2)
insert into butacas (cod_butaca,id_sala)
values('G2',2)
insert into butacas (cod_butaca,id_sala)
values('G3',2)
insert into butacas (cod_butaca,id_sala)
values('G4',2)
insert into butacas (cod_butaca,id_sala)
values('G5',2)
insert into butacas (cod_butaca,id_sala)
values('G6',2)
insert into butacas (cod_butaca,id_sala)
values('G7',2)
insert into butacas (cod_butaca,id_sala)
values('G8',2)
insert into butacas (cod_butaca,id_sala)
values('G9',2)
insert into butacas (cod_butaca,id_sala)
values('G10',2)

insert into butacas (cod_butaca,id_sala)
values('H1',2)
insert into butacas (cod_butaca,id_sala)
values('H2',2)
insert into butacas (cod_butaca,id_sala)
values('H3',2)
insert into butacas (cod_butaca,id_sala)
values('H4',2)
insert into butacas (cod_butaca,id_sala)
values('H5',2)
insert into butacas (cod_butaca,id_sala)
values('H6',2)
insert into butacas (cod_butaca,id_sala)
values('H7',2)
insert into butacas (cod_butaca,id_sala)
values('H8',2)
insert into butacas (cod_butaca,id_sala)
values('H9',2)
insert into butacas (cod_butaca,id_sala)
values('H10',2)

insert into butacas (cod_butaca,id_sala)
values('I1',2)
insert into butacas (cod_butaca,id_sala)
values('I2',2)
insert into butacas (cod_butaca,id_sala)
values('I3',2)
insert into butacas (cod_butaca,id_sala)
values('I4',2)
insert into butacas (cod_butaca,id_sala)
values('I5',2)
insert into butacas (cod_butaca,id_sala)
values('I6',2)
insert into butacas (cod_butaca,id_sala)
values('I7',2)
insert into butacas (cod_butaca,id_sala)
values('I8',2)
insert into butacas (cod_butaca,id_sala)
values('I9',2)
insert into butacas (cod_butaca,id_sala)
values('I10',2)

insert into butacas (cod_butaca,id_sala)
values('J1',2)
insert into butacas (cod_butaca,id_sala)
values('J2',2)
insert into butacas (cod_butaca,id_sala)
values('J3',2)
insert into butacas (cod_butaca,id_sala)
values('J4',2)
insert into butacas (cod_butaca,id_sala)
values('J5',2)
insert into butacas (cod_butaca,id_sala)
values('J6',2)
insert into butacas (cod_butaca,id_sala)
values('J7',2)
insert into butacas (cod_butaca,id_sala)
values('J8',2)
insert into butacas (cod_butaca,id_sala)
values('J9',2)
insert into butacas (cod_butaca,id_sala)
values('J10',2)






insert into butacas (cod_butaca,id_sala)
values('A1',3)
insert into butacas (cod_butaca,id_sala)
values('A2',3)
insert into butacas (cod_butaca,id_sala)
values('A3',3)
insert into butacas (cod_butaca,id_sala)
values('A4',3)
insert into butacas (cod_butaca,id_sala)
values('A5',3)
insert into butacas (cod_butaca,id_sala)
values('A6',3)
insert into butacas (cod_butaca,id_sala)
values('A7',3)
insert into butacas (cod_butaca,id_sala)
values('A8',3)
insert into butacas (cod_butaca,id_sala)
values('A9',3)
insert into butacas (cod_butaca,id_sala)
values('A10',3)

insert into butacas (cod_butaca,id_sala)
values('B1',3)
insert into butacas (cod_butaca,id_sala)
values('B2',3)
insert into butacas (cod_butaca,id_sala)
values('B3',3)
insert into butacas (cod_butaca,id_sala)
values('B4',3)
insert into butacas (cod_butaca,id_sala)
values('B5',3)
insert into butacas (cod_butaca,id_sala)
values('B6',3)
insert into butacas (cod_butaca,id_sala)
values('B7',3)
insert into butacas (cod_butaca,id_sala)
values('B8',3)
insert into butacas (cod_butaca,id_sala)
values('B9',3)
insert into butacas (cod_butaca,id_sala)
values('B10',3)

insert into butacas (cod_butaca,id_sala)
values('C1',3)
insert into butacas (cod_butaca,id_sala)
values('C2',3)
insert into butacas (cod_butaca,id_sala)
values('C3',3)
insert into butacas (cod_butaca,id_sala)
values('C4',3)
insert into butacas (cod_butaca,id_sala)
values('C5',3)
insert into butacas (cod_butaca,id_sala)
values('C6',3)
insert into butacas (cod_butaca,id_sala)
values('C7',3)
insert into butacas (cod_butaca,id_sala)
values('C8',3)
insert into butacas (cod_butaca,id_sala)
values('C9',3)
insert into butacas (cod_butaca,id_sala)
values('C10',3)

insert into butacas (cod_butaca,id_sala)
values('D1',3)
insert into butacas (cod_butaca,id_sala)
values('D2',3)
insert into butacas (cod_butaca,id_sala)
values('D3',3)
insert into butacas (cod_butaca,id_sala)
values('D4',3)
insert into butacas (cod_butaca,id_sala)
values('D5',3)
insert into butacas (cod_butaca,id_sala)
values('D6',3)
insert into butacas (cod_butaca,id_sala)
values('D7',3)
insert into butacas (cod_butaca,id_sala)
values('D8',3)
insert into butacas (cod_butaca,id_sala)
values('D9',3)
insert into butacas (cod_butaca,id_sala)
values('D10',3)

insert into butacas (cod_butaca,id_sala)
values('E1',3)
insert into butacas (cod_butaca,id_sala)
values('E2',3)
insert into butacas (cod_butaca,id_sala)
values('E3',3)
insert into butacas (cod_butaca,id_sala)
values('E4',3)
insert into butacas (cod_butaca,id_sala)
values('E5',3)
insert into butacas (cod_butaca,id_sala)
values('E6',3)
insert into butacas (cod_butaca,id_sala)
values('E7',3)
insert into butacas (cod_butaca,id_sala)
values('E8',3)
insert into butacas (cod_butaca,id_sala)
values('E9',3)
insert into butacas (cod_butaca,id_sala)
values('E10',3)

insert into butacas (cod_butaca,id_sala)
values('F1',3)
insert into butacas (cod_butaca,id_sala)
values('F2',3)
insert into butacas (cod_butaca,id_sala)
values('F3',3)
insert into butacas (cod_butaca,id_sala)
values('F4',3)
insert into butacas (cod_butaca,id_sala)
values('F5',3)
insert into butacas (cod_butaca,id_sala)
values('F6',3)
insert into butacas (cod_butaca,id_sala)
values('F7',3)
insert into butacas (cod_butaca,id_sala)
values('F8',3)
insert into butacas (cod_butaca,id_sala)
values('F9',3)
insert into butacas (cod_butaca,id_sala)
values('F10',3)

insert into butacas (cod_butaca,id_sala)
values('G1',3)
insert into butacas (cod_butaca,id_sala)
values('G2',3)
insert into butacas (cod_butaca,id_sala)
values('G3',3)
insert into butacas (cod_butaca,id_sala)
values('G4',3)
insert into butacas (cod_butaca,id_sala)
values('G5',3)
insert into butacas (cod_butaca,id_sala)
values('G6',3)
insert into butacas (cod_butaca,id_sala)
values('G7',3)
insert into butacas (cod_butaca,id_sala)
values('G8',3)
insert into butacas (cod_butaca,id_sala)
values('G9',3)
insert into butacas (cod_butaca,id_sala)
values('G10',3)

insert into butacas (cod_butaca,id_sala)
values('H1',3)
insert into butacas (cod_butaca,id_sala)
values('H2',3)
insert into butacas (cod_butaca,id_sala)
values('H3',3)
insert into butacas (cod_butaca,id_sala)
values('H4',3)
insert into butacas (cod_butaca,id_sala)
values('H5',3)
insert into butacas (cod_butaca,id_sala)
values('H6',3)
insert into butacas (cod_butaca,id_sala)
values('H7',3)
insert into butacas (cod_butaca,id_sala)
values('H8',3)
insert into butacas (cod_butaca,id_sala)
values('H9',3)
insert into butacas (cod_butaca,id_sala)
values('H10',3)

insert into butacas (cod_butaca,id_sala)
values('I1',3)
insert into butacas (cod_butaca,id_sala)
values('I2',3)
insert into butacas (cod_butaca,id_sala)
values('I3',3)
insert into butacas (cod_butaca,id_sala)
values('I4',3)
insert into butacas (cod_butaca,id_sala)
values('I5',3)
insert into butacas (cod_butaca,id_sala)
values('I6',3)
insert into butacas (cod_butaca,id_sala)
values('I7',3)
insert into butacas (cod_butaca,id_sala)
values('I8',3)
insert into butacas (cod_butaca,id_sala)
values('I9',3)
insert into butacas (cod_butaca,id_sala)
values('I10',3)

insert into butacas (cod_butaca,id_sala)
values('J1',3)
insert into butacas (cod_butaca,id_sala)
values('J2',3)
insert into butacas (cod_butaca,id_sala)
values('J3',3)
insert into butacas (cod_butaca,id_sala)
values('J4',3)
insert into butacas (cod_butaca,id_sala)
values('J5',3)
insert into butacas (cod_butaca,id_sala)
values('J6',3)
insert into butacas (cod_butaca,id_sala)
values('J7',3)
insert into butacas (cod_butaca,id_sala)
values('J8',3)
insert into butacas (cod_butaca,id_sala)
values('J9',3)
insert into butacas (cod_butaca,id_sala)
values('J10',3)

insert into butacas (cod_butaca,id_sala)
values('A1',4)
insert into butacas (cod_butaca,id_sala)
values('A2',4)
insert into butacas (cod_butaca,id_sala)
values('A3',4)
insert into butacas (cod_butaca,id_sala)
values('A4',4)
insert into butacas (cod_butaca,id_sala)
values('A5',4)
insert into butacas (cod_butaca,id_sala)
values('A6',4)
insert into butacas (cod_butaca,id_sala)
values('A7',4)
insert into butacas (cod_butaca,id_sala)
values('A8',4)
insert into butacas (cod_butaca,id_sala)
values('A9',4)
insert into butacas (cod_butaca,id_sala)
values('A10',4)

insert into butacas (cod_butaca,id_sala)
values('B1',4)
insert into butacas (cod_butaca,id_sala)
values('B2',4)
insert into butacas (cod_butaca,id_sala)
values('B3',4)
insert into butacas (cod_butaca,id_sala)
values('B4',4)
insert into butacas (cod_butaca,id_sala)
values('B5',4)
insert into butacas (cod_butaca,id_sala)
values('B6',4)
insert into butacas (cod_butaca,id_sala)
values('B7',4)
insert into butacas (cod_butaca,id_sala)
values('B8',4)
insert into butacas (cod_butaca,id_sala)
values('B9',4)
insert into butacas (cod_butaca,id_sala)
values('B10',4)

insert into butacas (cod_butaca,id_sala)
values('C1',4)
insert into butacas (cod_butaca,id_sala)
values('C2',4)
insert into butacas (cod_butaca,id_sala)
values('C3',4)
insert into butacas (cod_butaca,id_sala)
values('C4',4)
insert into butacas (cod_butaca,id_sala)
values('C5',4)
insert into butacas (cod_butaca,id_sala)
values('C6',4)
insert into butacas (cod_butaca,id_sala)
values('C7',4)
insert into butacas (cod_butaca,id_sala)
values('C8',4)
insert into butacas (cod_butaca,id_sala)
values('C9',4)
insert into butacas (cod_butaca,id_sala)
values('C10',4)

insert into butacas (cod_butaca,id_sala)
values('D1',4)
insert into butacas (cod_butaca,id_sala)
values('D2',4)
insert into butacas (cod_butaca,id_sala)
values('D3',4)
insert into butacas (cod_butaca,id_sala)
values('D4',4)
insert into butacas (cod_butaca,id_sala)
values('D5',4)
insert into butacas (cod_butaca,id_sala)
values('D6',4)
insert into butacas (cod_butaca,id_sala)
values('D7',4)
insert into butacas (cod_butaca,id_sala)
values('D8',4)
insert into butacas (cod_butaca,id_sala)
values('D9',4)
insert into butacas (cod_butaca,id_sala)
values('D10',4)

insert into butacas (cod_butaca,id_sala)
values('E1',4)
insert into butacas (cod_butaca,id_sala)
values('E2',4)
insert into butacas (cod_butaca,id_sala)
values('E3',4)
insert into butacas (cod_butaca,id_sala)
values('E4',4)
insert into butacas (cod_butaca,id_sala)
values('E5',4)
insert into butacas (cod_butaca,id_sala)
values('E6',4)
insert into butacas (cod_butaca,id_sala)
values('E7',4)
insert into butacas (cod_butaca,id_sala)
values('E8',4)
insert into butacas (cod_butaca,id_sala)
values('E9',4)
insert into butacas (cod_butaca,id_sala)
values('E10',4)

insert into butacas (cod_butaca,id_sala)
values('F1',4)
insert into butacas (cod_butaca,id_sala)
values('F2',4)
insert into butacas (cod_butaca,id_sala)
values('F3',4)
insert into butacas (cod_butaca,id_sala)
values('F4',4)
insert into butacas (cod_butaca,id_sala)
values('F5',4)
insert into butacas (cod_butaca,id_sala)
values('F6',4)
insert into butacas (cod_butaca,id_sala)
values('F7',4)
insert into butacas (cod_butaca,id_sala)
values('F8',4)
insert into butacas (cod_butaca,id_sala)
values('F9',4)
insert into butacas (cod_butaca,id_sala)
values('F10',4)

insert into butacas (cod_butaca,id_sala)
values('G1',4)
insert into butacas (cod_butaca,id_sala)
values('G2',4)
insert into butacas (cod_butaca,id_sala)
values('G3',4)
insert into butacas (cod_butaca,id_sala)
values('G4',4)
insert into butacas (cod_butaca,id_sala)
values('G5',4)
insert into butacas (cod_butaca,id_sala)
values('G6',4)
insert into butacas (cod_butaca,id_sala)
values('G7',4)
insert into butacas (cod_butaca,id_sala)
values('G8',4)
insert into butacas (cod_butaca,id_sala)
values('G9',4)
insert into butacas (cod_butaca,id_sala)
values('G10',4)

insert into butacas (cod_butaca,id_sala)
values('H1',4)
insert into butacas (cod_butaca,id_sala)
values('H2',4)
insert into butacas (cod_butaca,id_sala)
values('H3',4)
insert into butacas (cod_butaca,id_sala)
values('H4',4)
insert into butacas (cod_butaca,id_sala)
values('H5',4)
insert into butacas (cod_butaca,id_sala)
values('H6',4)
insert into butacas (cod_butaca,id_sala)
values('H7',4)
insert into butacas (cod_butaca,id_sala)
values('H8',4)
insert into butacas (cod_butaca,id_sala)
values('H9',4)
insert into butacas (cod_butaca,id_sala)
values('H10',4)

insert into butacas (cod_butaca,id_sala)
values('I1',4)
insert into butacas (cod_butaca,id_sala)
values('I2',4)
insert into butacas (cod_butaca,id_sala)
values('I3',4)
insert into butacas (cod_butaca,id_sala)
values('I4',4)
insert into butacas (cod_butaca,id_sala)
values('I5',4)
insert into butacas (cod_butaca,id_sala)
values('I6',4)
insert into butacas (cod_butaca,id_sala)
values('I7',4)
insert into butacas (cod_butaca,id_sala)
values('I8',4)
insert into butacas (cod_butaca,id_sala)
values('I9',4)
insert into butacas (cod_butaca,id_sala)
values('I10',4)

insert into butacas (cod_butaca,id_sala)
values('J1',4)
insert into butacas (cod_butaca,id_sala)
values('J2',4)
insert into butacas (cod_butaca,id_sala)
values('J3',4)
insert into butacas (cod_butaca,id_sala)
values('J4',4)
insert into butacas (cod_butaca,id_sala)
values('J5',4)
insert into butacas (cod_butaca,id_sala)
values('J6',4)
insert into butacas (cod_butaca,id_sala)
values('J7',4)
insert into butacas (cod_butaca,id_sala)
values('J8',4)
insert into butacas (cod_butaca,id_sala)
values('J9',4)
insert into butacas (cod_butaca,id_sala)
values('J10',4)

insert into butacas (cod_butaca,id_sala)
values('A1',5)
insert into butacas (cod_butaca,id_sala)
values('A2',5)
insert into butacas (cod_butaca,id_sala)
values('A3',5)
insert into butacas (cod_butaca,id_sala)
values('A4',5)
insert into butacas (cod_butaca,id_sala)
values('A5',5)
insert into butacas (cod_butaca,id_sala)
values('A6',5)
insert into butacas (cod_butaca,id_sala)
values('A7',5)
insert into butacas (cod_butaca,id_sala)
values('A8',5)
insert into butacas (cod_butaca,id_sala)
values('A9',5)
insert into butacas (cod_butaca,id_sala)
values('A10',5)

insert into butacas (cod_butaca,id_sala)
values('B1',5)
insert into butacas (cod_butaca,id_sala)
values('B2',5)
insert into butacas (cod_butaca,id_sala)
values('B3',5)
insert into butacas (cod_butaca,id_sala)
values('B4',5)
insert into butacas (cod_butaca,id_sala)
values('B5',5)
insert into butacas (cod_butaca,id_sala)
values('B6',5)
insert into butacas (cod_butaca,id_sala)
values('B7',5)
insert into butacas (cod_butaca,id_sala)
values('B8',5)
insert into butacas (cod_butaca,id_sala)
values('B9',5)
insert into butacas (cod_butaca,id_sala)
values('B10',5)

insert into butacas (cod_butaca,id_sala)
values('C1',5)
insert into butacas (cod_butaca,id_sala)
values('C2',5)
insert into butacas (cod_butaca,id_sala)
values('C3',5)
insert into butacas (cod_butaca,id_sala)
values('C4',5)
insert into butacas (cod_butaca,id_sala)
values('C5',5)
insert into butacas (cod_butaca,id_sala)
values('C6',5)
insert into butacas (cod_butaca,id_sala)
values('C7',5)
insert into butacas (cod_butaca,id_sala)
values('C8',5)
insert into butacas (cod_butaca,id_sala)
values('C9',5)
insert into butacas (cod_butaca,id_sala)
values('C10',5)

insert into butacas (cod_butaca,id_sala)
values('D1',5)
insert into butacas (cod_butaca,id_sala)
values('D2',5)
insert into butacas (cod_butaca,id_sala)
values('D3',5)
insert into butacas (cod_butaca,id_sala)
values('D4',5)
insert into butacas (cod_butaca,id_sala)
values('D5',5)
insert into butacas (cod_butaca,id_sala)
values('D6',5)
insert into butacas (cod_butaca,id_sala)
values('D7',5)
insert into butacas (cod_butaca,id_sala)
values('D8',5)
insert into butacas (cod_butaca,id_sala)
values('D9',5)
insert into butacas (cod_butaca,id_sala)
values('D10',5)

insert into butacas (cod_butaca,id_sala)
values('E1',5)
insert into butacas (cod_butaca,id_sala)
values('E2',5)
insert into butacas (cod_butaca,id_sala)
values('E3',5)
insert into butacas (cod_butaca,id_sala)
values('E4',5)
insert into butacas (cod_butaca,id_sala)
values('E5',5)
insert into butacas (cod_butaca,id_sala)
values('E6',5)
insert into butacas (cod_butaca,id_sala)
values('E7',5)
insert into butacas (cod_butaca,id_sala)
values('E8',5)
insert into butacas (cod_butaca,id_sala)
values('E9',5)
insert into butacas (cod_butaca,id_sala)
values('E10',5)

insert into butacas (cod_butaca,id_sala)
values('F1',5)
insert into butacas (cod_butaca,id_sala)
values('F2',5)
insert into butacas (cod_butaca,id_sala)
values('F3',5)
insert into butacas (cod_butaca,id_sala)
values('F4',5)
insert into butacas (cod_butaca,id_sala)
values('F5',5)
insert into butacas (cod_butaca,id_sala)
values('F6',5)
insert into butacas (cod_butaca,id_sala)
values('F7',5)
insert into butacas (cod_butaca,id_sala)
values('F8',5)
insert into butacas (cod_butaca,id_sala)
values('F9',5)
insert into butacas (cod_butaca,id_sala)
values('F10',5)

insert into butacas (cod_butaca,id_sala)
values('G1',5)
insert into butacas (cod_butaca,id_sala)
values('G2',5)
insert into butacas (cod_butaca,id_sala)
values('G3',5)
insert into butacas (cod_butaca,id_sala)
values('G4',5)
insert into butacas (cod_butaca,id_sala)
values('G5',5)
insert into butacas (cod_butaca,id_sala)
values('G6',5)
insert into butacas (cod_butaca,id_sala)
values('G7',5)
insert into butacas (cod_butaca,id_sala)
values('G8',5)
insert into butacas (cod_butaca,id_sala)
values('G9',5)
insert into butacas (cod_butaca,id_sala)
values('G10',5)

insert into butacas (cod_butaca,id_sala)
values('H1',5)
insert into butacas (cod_butaca,id_sala)
values('H2',5)
insert into butacas (cod_butaca,id_sala)
values('H3',5)
insert into butacas (cod_butaca,id_sala)
values('H4',5)
insert into butacas (cod_butaca,id_sala)
values('H5',5)
insert into butacas (cod_butaca,id_sala)
values('H6',5)
insert into butacas (cod_butaca,id_sala)
values('H7',5)
insert into butacas (cod_butaca,id_sala)
values('H8',5)
insert into butacas (cod_butaca,id_sala)
values('H9',5)
insert into butacas (cod_butaca,id_sala)
values('H10',5)

insert into butacas (cod_butaca,id_sala)
values('I1',5)
insert into butacas (cod_butaca,id_sala)
values('I2',5)
insert into butacas (cod_butaca,id_sala)
values('I3',5)
insert into butacas (cod_butaca,id_sala)
values('I4',5)
insert into butacas (cod_butaca,id_sala)
values('I5',5)
insert into butacas (cod_butaca,id_sala)
values('I6',5)
insert into butacas (cod_butaca,id_sala)
values('I7',5)
insert into butacas (cod_butaca,id_sala)
values('I8',5)
insert into butacas (cod_butaca,id_sala)
values('I9',5)
insert into butacas (cod_butaca,id_sala)
values('I10',5)

insert into butacas (cod_butaca,id_sala)
values('J1',5)
insert into butacas (cod_butaca,id_sala)
values('J2',5)
insert into butacas (cod_butaca,id_sala)
values('J3',5)
insert into butacas (cod_butaca,id_sala)
values('J4',5)
insert into butacas (cod_butaca,id_sala)
values('J5',5)
insert into butacas (cod_butaca,id_sala)
values('J6',5)
insert into butacas (cod_butaca,id_sala)
values('J7',5)
insert into butacas (cod_butaca,id_sala)
values('J8',5)
insert into butacas (cod_butaca,id_sala)
values('J9',5)
insert into butacas (cod_butaca,id_sala)
values('J10',5)

insert into butacas (cod_butaca,id_sala)
values('A1',6)
insert into butacas (cod_butaca,id_sala)
values('A2',6)
insert into butacas (cod_butaca,id_sala)
values('A3',6)
insert into butacas (cod_butaca,id_sala)
values('A4',6)
insert into butacas (cod_butaca,id_sala)
values('A5',6)
insert into butacas (cod_butaca,id_sala)
values('A6',6)
insert into butacas (cod_butaca,id_sala)
values('A7',6)
insert into butacas (cod_butaca,id_sala)
values('A8',6)
insert into butacas (cod_butaca,id_sala)
values('A9',6)
insert into butacas (cod_butaca,id_sala)
values('A10',6)

insert into butacas (cod_butaca,id_sala)
values('B1',6)
insert into butacas (cod_butaca,id_sala)
values('B2',6)
insert into butacas (cod_butaca,id_sala)
values('B3',6)
insert into butacas (cod_butaca,id_sala)
values('B4',6)
insert into butacas (cod_butaca,id_sala)
values('B5',6)
insert into butacas (cod_butaca,id_sala)
values('B6',6)
insert into butacas (cod_butaca,id_sala)
values('B7',6)
insert into butacas (cod_butaca,id_sala)
values('B8',6)
insert into butacas (cod_butaca,id_sala)
values('B9',6)
insert into butacas (cod_butaca,id_sala)
values('B10',6)

insert into butacas (cod_butaca,id_sala)
values('C1',6)
insert into butacas (cod_butaca,id_sala)
values('C2',6)
insert into butacas (cod_butaca,id_sala)
values('C3',6)
insert into butacas (cod_butaca,id_sala)
values('C4',6)
insert into butacas (cod_butaca,id_sala)
values('C5',6)
insert into butacas (cod_butaca,id_sala)
values('C6',6)
insert into butacas (cod_butaca,id_sala)
values('C7',6)
insert into butacas (cod_butaca,id_sala)
values('C8',6)
insert into butacas (cod_butaca,id_sala)
values('C9',6)
insert into butacas (cod_butaca,id_sala)
values('C10',6)

insert into butacas (cod_butaca,id_sala)
values('D1',6)
insert into butacas (cod_butaca,id_sala)
values('D2',6)
insert into butacas (cod_butaca,id_sala)
values('D3',6)
insert into butacas (cod_butaca,id_sala)
values('D4',6)
insert into butacas (cod_butaca,id_sala)
values('D5',6)
insert into butacas (cod_butaca,id_sala)
values('D6',6)
insert into butacas (cod_butaca,id_sala)
values('D7',6)
insert into butacas (cod_butaca,id_sala)
values('D8',6)
insert into butacas (cod_butaca,id_sala)
values('D9',6)
insert into butacas (cod_butaca,id_sala)
values('D10',6)

insert into butacas (cod_butaca,id_sala)
values('E1',6)
insert into butacas (cod_butaca,id_sala)
values('E2',6)
insert into butacas (cod_butaca,id_sala)
values('E3',6)
insert into butacas (cod_butaca,id_sala)
values('E4',6)
insert into butacas (cod_butaca,id_sala)
values('E5',6)
insert into butacas (cod_butaca,id_sala)
values('E6',6)
insert into butacas (cod_butaca,id_sala)
values('E7',6)
insert into butacas (cod_butaca,id_sala)
values('E8',6)
insert into butacas (cod_butaca,id_sala)
values('E9',6)
insert into butacas (cod_butaca,id_sala)
values('E10',6)

insert into butacas (cod_butaca,id_sala)
values('F1',6)
insert into butacas (cod_butaca,id_sala)
values('F2',6)
insert into butacas (cod_butaca,id_sala)
values('F3',6)
insert into butacas (cod_butaca,id_sala)
values('F4',6)
insert into butacas (cod_butaca,id_sala)
values('F5',6)
insert into butacas (cod_butaca,id_sala)
values('F6',6)
insert into butacas (cod_butaca,id_sala)
values('F7',6)
insert into butacas (cod_butaca,id_sala)
values('F8',6)
insert into butacas (cod_butaca,id_sala)
values('F9',6)
insert into butacas (cod_butaca,id_sala)
values('F10',6)

insert into butacas (cod_butaca,id_sala)
values('G1',6)
insert into butacas (cod_butaca,id_sala)
values('G2',6)
insert into butacas (cod_butaca,id_sala)
values('G3',6)
insert into butacas (cod_butaca,id_sala)
values('G4',6)
insert into butacas (cod_butaca,id_sala)
values('G5',6)
insert into butacas (cod_butaca,id_sala)
values('G6',6)
insert into butacas (cod_butaca,id_sala)
values('G7',6)
insert into butacas (cod_butaca,id_sala)
values('G8',6)
insert into butacas (cod_butaca,id_sala)
values('G9',6)
insert into butacas (cod_butaca,id_sala)
values('G10',6)

insert into butacas (cod_butaca,id_sala)
values('H1',6)
insert into butacas (cod_butaca,id_sala)
values('H2',6)
insert into butacas (cod_butaca,id_sala)
values('H3',6)
insert into butacas (cod_butaca,id_sala)
values('H4',6)
insert into butacas (cod_butaca,id_sala)
values('H5',6)
insert into butacas (cod_butaca,id_sala)
values('H6',6)
insert into butacas (cod_butaca,id_sala)
values('H7',6)
insert into butacas (cod_butaca,id_sala)
values('H8',6)
insert into butacas (cod_butaca,id_sala)
values('H9',6)
insert into butacas (cod_butaca,id_sala)
values('H10',6)

insert into butacas (cod_butaca,id_sala)
values('I1',6)
insert into butacas (cod_butaca,id_sala)
values('I2',6)
insert into butacas (cod_butaca,id_sala)
values('I3',6)
insert into butacas (cod_butaca,id_sala)
values('I4',6)
insert into butacas (cod_butaca,id_sala)
values('I5',6)
insert into butacas (cod_butaca,id_sala)
values('I6',6)
insert into butacas (cod_butaca,id_sala)
values('I7',6)
insert into butacas (cod_butaca,id_sala)
values('I8',6)
insert into butacas (cod_butaca,id_sala)
values('I9',6)
insert into butacas (cod_butaca,id_sala)
values('I10',6)

insert into butacas (cod_butaca,id_sala)
values('J1',6)
insert into butacas (cod_butaca,id_sala)
values('J2',6)
insert into butacas (cod_butaca,id_sala)
values('J3',6)
insert into butacas (cod_butaca,id_sala)
values('J4',6)
insert into butacas (cod_butaca,id_sala)
values('J5',6)
insert into butacas (cod_butaca,id_sala)
values('J6',6)
insert into butacas (cod_butaca,id_sala)
values('J7',6)
insert into butacas (cod_butaca,id_sala)
values('J8',6)
insert into butacas (cod_butaca,id_sala)
values('J9',6)
insert into butacas (cod_butaca,id_sala)
values('J10',6)

insert into butacas (cod_butaca,id_sala)
values('A1',7)
insert into butacas (cod_butaca,id_sala)
values('A2',7)
insert into butacas (cod_butaca,id_sala)
values('A3',7)
insert into butacas (cod_butaca,id_sala)
values('A4',7)
insert into butacas (cod_butaca,id_sala)
values('A5',7)
insert into butacas (cod_butaca,id_sala)
values('A6',7)
insert into butacas (cod_butaca,id_sala)
values('A7',7)
insert into butacas (cod_butaca,id_sala)
values('A8',7)
insert into butacas (cod_butaca,id_sala)
values('A9',7)
insert into butacas (cod_butaca,id_sala)
values('A10',7)

insert into butacas (cod_butaca,id_sala)
values('B1',7)
insert into butacas (cod_butaca,id_sala)
values('B2',7)
insert into butacas (cod_butaca,id_sala)
values('B3',7)
insert into butacas (cod_butaca,id_sala)
values('B4',7)
insert into butacas (cod_butaca,id_sala)
values('B5',7)
insert into butacas (cod_butaca,id_sala)
values('B6',7)
insert into butacas (cod_butaca,id_sala)
values('B7',7)
insert into butacas (cod_butaca,id_sala)
values('B8',7)
insert into butacas (cod_butaca,id_sala)
values('B9',7)
insert into butacas (cod_butaca,id_sala)
values('B10',7)

insert into butacas (cod_butaca,id_sala)
values('C1',7)
insert into butacas (cod_butaca,id_sala)
values('C2',7)
insert into butacas (cod_butaca,id_sala)
values('C3',7)
insert into butacas (cod_butaca,id_sala)
values('C4',7)
insert into butacas (cod_butaca,id_sala)
values('C5',7)
insert into butacas (cod_butaca,id_sala)
values('C6',7)
insert into butacas (cod_butaca,id_sala)
values('C7',7)
insert into butacas (cod_butaca,id_sala)
values('C8',7)
insert into butacas (cod_butaca,id_sala)
values('C9',7)
insert into butacas (cod_butaca,id_sala)
values('C10',7)

insert into butacas (cod_butaca,id_sala)
values('D1',7)
insert into butacas (cod_butaca,id_sala)
values('D2',7)
insert into butacas (cod_butaca,id_sala)
values('D3',7)
insert into butacas (cod_butaca,id_sala)
values('D4',7)
insert into butacas (cod_butaca,id_sala)
values('D5',7)
insert into butacas (cod_butaca,id_sala)
values('D6',7)
insert into butacas (cod_butaca,id_sala)
values('D7',7)
insert into butacas (cod_butaca,id_sala)
values('D8',7)
insert into butacas (cod_butaca,id_sala)
values('D9',7)
insert into butacas (cod_butaca,id_sala)
values('D10',7)

insert into butacas (cod_butaca,id_sala)
values('E1',7)
insert into butacas (cod_butaca,id_sala)
values('E2',7)
insert into butacas (cod_butaca,id_sala)
values('E3',7)
insert into butacas (cod_butaca,id_sala)
values('E4',7)
insert into butacas (cod_butaca,id_sala)
values('E5',7)
insert into butacas (cod_butaca,id_sala)
values('E6',7)
insert into butacas (cod_butaca,id_sala)
values('E7',7)
insert into butacas (cod_butaca,id_sala)
values('E8',7)
insert into butacas (cod_butaca,id_sala)
values('E9',7)
insert into butacas (cod_butaca,id_sala)
values('E10',7)

insert into butacas (cod_butaca,id_sala)
values('F1',7)
insert into butacas (cod_butaca,id_sala)
values('F2',7)
insert into butacas (cod_butaca,id_sala)
values('F3',7)
insert into butacas (cod_butaca,id_sala)
values('F4',7)
insert into butacas (cod_butaca,id_sala)
values('F5',7)
insert into butacas (cod_butaca,id_sala)
values('F6',7)
insert into butacas (cod_butaca,id_sala)
values('F7',7)
insert into butacas (cod_butaca,id_sala)
values('F8',7)
insert into butacas (cod_butaca,id_sala)
values('F9',7)
insert into butacas (cod_butaca,id_sala)
values('F10',7)

insert into butacas (cod_butaca,id_sala)
values('G1',7)
insert into butacas (cod_butaca,id_sala)
values('G2',7)
insert into butacas (cod_butaca,id_sala)
values('G3',7)
insert into butacas (cod_butaca,id_sala)
values('G4',7)
insert into butacas (cod_butaca,id_sala)
values('G5',7)
insert into butacas (cod_butaca,id_sala)
values('G6',7)
insert into butacas (cod_butaca,id_sala)
values('G7',7)
insert into butacas (cod_butaca,id_sala)
values('G8',7)
insert into butacas (cod_butaca,id_sala)
values('G9',7)
insert into butacas (cod_butaca,id_sala)
values('G10',7)

insert into butacas (cod_butaca,id_sala)
values('H1',7)
insert into butacas (cod_butaca,id_sala)
values('H2',7)
insert into butacas (cod_butaca,id_sala)
values('H3',7)
insert into butacas (cod_butaca,id_sala)
values('H4',7)
insert into butacas (cod_butaca,id_sala)
values('H5',7)
insert into butacas (cod_butaca,id_sala)
values('H6',7)
insert into butacas (cod_butaca,id_sala)
values('H7',7)
insert into butacas (cod_butaca,id_sala)
values('H8',7)
insert into butacas (cod_butaca,id_sala)
values('H9',7)
insert into butacas (cod_butaca,id_sala)
values('H10',7)

insert into butacas (cod_butaca,id_sala)
values('I1',7)
insert into butacas (cod_butaca,id_sala)
values('I2',7)
insert into butacas (cod_butaca,id_sala)
values('I3',7)
insert into butacas (cod_butaca,id_sala)
values('I4',7)
insert into butacas (cod_butaca,id_sala)
values('I5',7)
insert into butacas (cod_butaca,id_sala)
values('I6',7)
insert into butacas (cod_butaca,id_sala)
values('I7',7)
insert into butacas (cod_butaca,id_sala)
values('I8',7)
insert into butacas (cod_butaca,id_sala)
values('I9',7)
insert into butacas (cod_butaca,id_sala)
values('I10',7)

insert into butacas (cod_butaca,id_sala)
values('J1',7)
insert into butacas (cod_butaca,id_sala)
values('J2',7)
insert into butacas (cod_butaca,id_sala)
values('J3',7)
insert into butacas (cod_butaca,id_sala)
values('J4',7)
insert into butacas (cod_butaca,id_sala)
values('J5',7)
insert into butacas (cod_butaca,id_sala)
values('J6',7)
insert into butacas (cod_butaca,id_sala)
values('J7',7)
insert into butacas (cod_butaca,id_sala)
values('J8',7)
insert into butacas (cod_butaca,id_sala)
values('J9',7)
insert into butacas (cod_butaca,id_sala)
values('J10',7)

insert into butacas (cod_butaca,id_sala)
values('A1',8)
insert into butacas (cod_butaca,id_sala)
values('A2',8)
insert into butacas (cod_butaca,id_sala)
values('A3',8)
insert into butacas (cod_butaca,id_sala)
values('A4',8)
insert into butacas (cod_butaca,id_sala)
values('A5',8)
insert into butacas (cod_butaca,id_sala)
values('A6',8)
insert into butacas (cod_butaca,id_sala)
values('A7',8)
insert into butacas (cod_butaca,id_sala)
values('A8',8)
insert into butacas (cod_butaca,id_sala)
values('A9',8)
insert into butacas (cod_butaca,id_sala)
values('A10',8)

insert into butacas (cod_butaca,id_sala)
values('B1',8)
insert into butacas (cod_butaca,id_sala)
values('B2',8)
insert into butacas (cod_butaca,id_sala)
values('B3',8)
insert into butacas (cod_butaca,id_sala)
values('B4',8)
insert into butacas (cod_butaca,id_sala)
values('B5',8)
insert into butacas (cod_butaca,id_sala)
values('B6',8)
insert into butacas (cod_butaca,id_sala)
values('B7',8)
insert into butacas (cod_butaca,id_sala)
values('B8',8)
insert into butacas (cod_butaca,id_sala)
values('B9',8)
insert into butacas (cod_butaca,id_sala)
values('B10',8)

insert into butacas (cod_butaca,id_sala)
values('C1',8)
insert into butacas (cod_butaca,id_sala)
values('C2',8)
insert into butacas (cod_butaca,id_sala)
values('C3',8)
insert into butacas (cod_butaca,id_sala)
values('C4',8)
insert into butacas (cod_butaca,id_sala)
values('C5',8)
insert into butacas (cod_butaca,id_sala)
values('C6',8)
insert into butacas (cod_butaca,id_sala)
values('C7',8)
insert into butacas (cod_butaca,id_sala)
values('C8',8)
insert into butacas (cod_butaca,id_sala)
values('C9',8)
insert into butacas (cod_butaca,id_sala)
values('C10',8)

insert into butacas (cod_butaca,id_sala)
values('D1',8)
insert into butacas (cod_butaca,id_sala)
values('D2',8)
insert into butacas (cod_butaca,id_sala)
values('D3',8)
insert into butacas (cod_butaca,id_sala)
values('D4',8)
insert into butacas (cod_butaca,id_sala)
values('D5',8)
insert into butacas (cod_butaca,id_sala)
values('D6',8)
insert into butacas (cod_butaca,id_sala)
values('D7',8)
insert into butacas (cod_butaca,id_sala)
values('D8',8)
insert into butacas (cod_butaca,id_sala)
values('D9',8)
insert into butacas (cod_butaca,id_sala)
values('D10',8)

insert into butacas (cod_butaca,id_sala)
values('E1',8)
insert into butacas (cod_butaca,id_sala)
values('E2',8)
insert into butacas (cod_butaca,id_sala)
values('E3',8)
insert into butacas (cod_butaca,id_sala)
values('E4',8)
insert into butacas (cod_butaca,id_sala)
values('E5',8)
insert into butacas (cod_butaca,id_sala)
values('E6',8)
insert into butacas (cod_butaca,id_sala)
values('E7',8)
insert into butacas (cod_butaca,id_sala)
values('E8',8)
insert into butacas (cod_butaca,id_sala)
values('E9',8)
insert into butacas (cod_butaca,id_sala)
values('E10',8)

insert into butacas (cod_butaca,id_sala)
values('F1',8)
insert into butacas (cod_butaca,id_sala)
values('F2',8)
insert into butacas (cod_butaca,id_sala)
values('F3',8)
insert into butacas (cod_butaca,id_sala)
values('F4',8)
insert into butacas (cod_butaca,id_sala)
values('F5',8)
insert into butacas (cod_butaca,id_sala)
values('F6',8)
insert into butacas (cod_butaca,id_sala)
values('F7',8)
insert into butacas (cod_butaca,id_sala)
values('F8',8)
insert into butacas (cod_butaca,id_sala)
values('F9',8)
insert into butacas (cod_butaca,id_sala)
values('F10',8)

insert into butacas (cod_butaca,id_sala)
values('G1',8)
insert into butacas (cod_butaca,id_sala)
values('G2',8)
insert into butacas (cod_butaca,id_sala)
values('G3',8)
insert into butacas (cod_butaca,id_sala)
values('G4',8)
insert into butacas (cod_butaca,id_sala)
values('G5',8)
insert into butacas (cod_butaca,id_sala)
values('G6',8)
insert into butacas (cod_butaca,id_sala)
values('G7',8)
insert into butacas (cod_butaca,id_sala)
values('G8',8)
insert into butacas (cod_butaca,id_sala)
values('G9',8)
insert into butacas (cod_butaca,id_sala)
values('G10',8)

insert into butacas (cod_butaca,id_sala)
values('H1',8)
insert into butacas (cod_butaca,id_sala)
values('H2',8)
insert into butacas (cod_butaca,id_sala)
values('H3',8)
insert into butacas (cod_butaca,id_sala)
values('H4',8)
insert into butacas (cod_butaca,id_sala)
values('H5',8)
insert into butacas (cod_butaca,id_sala)
values('H6',8)
insert into butacas (cod_butaca,id_sala)
values('H7',8)
insert into butacas (cod_butaca,id_sala)
values('H8',8)
insert into butacas (cod_butaca,id_sala)
values('H9',8)
insert into butacas (cod_butaca,id_sala)
values('H10',8)

insert into butacas (cod_butaca,id_sala)
values('I1',8)
insert into butacas (cod_butaca,id_sala)
values('I2',8)
insert into butacas (cod_butaca,id_sala)
values('I3',8)
insert into butacas (cod_butaca,id_sala)
values('I4',8)
insert into butacas (cod_butaca,id_sala)
values('I5',8)
insert into butacas (cod_butaca,id_sala)
values('I6',8)
insert into butacas (cod_butaca,id_sala)
values('I7',8)
insert into butacas (cod_butaca,id_sala)
values('I8',8)
insert into butacas (cod_butaca,id_sala)
values('I9',8)
insert into butacas (cod_butaca,id_sala)
values('I10',8)

insert into butacas (cod_butaca,id_sala)
values('J1',8)
insert into butacas (cod_butaca,id_sala)
values('J2',8)
insert into butacas (cod_butaca,id_sala)
values('J3',8)
insert into butacas (cod_butaca,id_sala)
values('J4',8)
insert into butacas (cod_butaca,id_sala)
values('J5',8)
insert into butacas (cod_butaca,id_sala)
values('J6',8)
insert into butacas (cod_butaca,id_sala)
values('J7',8)
insert into butacas (cod_butaca,id_sala)
values('J8',8)
insert into butacas (cod_butaca,id_sala)
values('J9',8)
insert into butacas (cod_butaca,id_sala)
values('J10',8)

insert into butacas (cod_butaca,id_sala)
values('A1',9)
insert into butacas (cod_butaca,id_sala)
values('A2',9)
insert into butacas (cod_butaca,id_sala)
values('A3',9)
insert into butacas (cod_butaca,id_sala)
values('A4',9)
insert into butacas (cod_butaca,id_sala)
values('A5',9)
insert into butacas (cod_butaca,id_sala)
values('A6',9)
insert into butacas (cod_butaca,id_sala)
values('A7',9)
insert into butacas (cod_butaca,id_sala)
values('A8',9)
insert into butacas (cod_butaca,id_sala)
values('A9',9)
insert into butacas (cod_butaca,id_sala)
values('A10',9)

insert into butacas (cod_butaca,id_sala)
values('B1',9)
insert into butacas (cod_butaca,id_sala)
values('B2',9)
insert into butacas (cod_butaca,id_sala)
values('B3',9)
insert into butacas (cod_butaca,id_sala)
values('B4',9)
insert into butacas (cod_butaca,id_sala)
values('B5',9)
insert into butacas (cod_butaca,id_sala)
values('B6',9)
insert into butacas (cod_butaca,id_sala)
values('B7',9)
insert into butacas (cod_butaca,id_sala)
values('B8',9)
insert into butacas (cod_butaca,id_sala)
values('B9',9)
insert into butacas (cod_butaca,id_sala)
values('B10',9)

insert into butacas (cod_butaca,id_sala)
values('C1',9)
insert into butacas (cod_butaca,id_sala)
values('C2',9)
insert into butacas (cod_butaca,id_sala)
values('C3',9)
insert into butacas (cod_butaca,id_sala)
values('C4',9)
insert into butacas (cod_butaca,id_sala)
values('C5',9)
insert into butacas (cod_butaca,id_sala)
values('C6',9)
insert into butacas (cod_butaca,id_sala)
values('C7',9)
insert into butacas (cod_butaca,id_sala)
values('C8',9)
insert into butacas (cod_butaca,id_sala)
values('C9',9)
insert into butacas (cod_butaca,id_sala)
values('C10',9)

insert into butacas (cod_butaca,id_sala)
values('D1',9)
insert into butacas (cod_butaca,id_sala)
values('D2',9)
insert into butacas (cod_butaca,id_sala)
values('D3',9)
insert into butacas (cod_butaca,id_sala)
values('D4',9)
insert into butacas (cod_butaca,id_sala)
values('D5',9)
insert into butacas (cod_butaca,id_sala)
values('D6',9)
insert into butacas (cod_butaca,id_sala)
values('D7',9)
insert into butacas (cod_butaca,id_sala)
values('D8',9)
insert into butacas (cod_butaca,id_sala)
values('D9',9)
insert into butacas (cod_butaca,id_sala)
values('D10',9)

insert into butacas (cod_butaca,id_sala)
values('E1',9)
insert into butacas (cod_butaca,id_sala)
values('E2',9)
insert into butacas (cod_butaca,id_sala)
values('E3',9)
insert into butacas (cod_butaca,id_sala)
values('E4',9)
insert into butacas (cod_butaca,id_sala)
values('E5',9)
insert into butacas (cod_butaca,id_sala)
values('E6',9)
insert into butacas (cod_butaca,id_sala)
values('E7',9)
insert into butacas (cod_butaca,id_sala)
values('E8',9)
insert into butacas (cod_butaca,id_sala)
values('E9',9)
insert into butacas (cod_butaca,id_sala)
values('E10',9)

insert into butacas (cod_butaca,id_sala)
values('F1',9)
insert into butacas (cod_butaca,id_sala)
values('F2',9)
insert into butacas (cod_butaca,id_sala)
values('F3',9)
insert into butacas (cod_butaca,id_sala)
values('F4',9)
insert into butacas (cod_butaca,id_sala)
values('F5',9)
insert into butacas (cod_butaca,id_sala)
values('F6',9)
insert into butacas (cod_butaca,id_sala)
values('F7',9)
insert into butacas (cod_butaca,id_sala)
values('F8',9)
insert into butacas (cod_butaca,id_sala)
values('F9',9)
insert into butacas (cod_butaca,id_sala)
values('F10',9)

insert into butacas (cod_butaca,id_sala)
values('G1',9)
insert into butacas (cod_butaca,id_sala)
values('G2',9)
insert into butacas (cod_butaca,id_sala)
values('G3',9)
insert into butacas (cod_butaca,id_sala)
values('G4',9)
insert into butacas (cod_butaca,id_sala)
values('G5',9)
insert into butacas (cod_butaca,id_sala)
values('G6',9)
insert into butacas (cod_butaca,id_sala)
values('G7',9)
insert into butacas (cod_butaca,id_sala)
values('G8',9)
insert into butacas (cod_butaca,id_sala)
values('G9',9)
insert into butacas (cod_butaca,id_sala)
values('G10',9)

insert into butacas (cod_butaca,id_sala)
values('H1',9)
insert into butacas (cod_butaca,id_sala)
values('H2',9)
insert into butacas (cod_butaca,id_sala)
values('H3',9)
insert into butacas (cod_butaca,id_sala)
values('H4',9)
insert into butacas (cod_butaca,id_sala)
values('H5',9)
insert into butacas (cod_butaca,id_sala)
values('H6',9)
insert into butacas (cod_butaca,id_sala)
values('H7',9)
insert into butacas (cod_butaca,id_sala)
values('H8',9)
insert into butacas (cod_butaca,id_sala)
values('H9',9)
insert into butacas (cod_butaca,id_sala)
values('H10',9)

insert into butacas (cod_butaca,id_sala)
values('I1',9)
insert into butacas (cod_butaca,id_sala)
values('I2',9)
insert into butacas (cod_butaca,id_sala)
values('I3',9)
insert into butacas (cod_butaca,id_sala)
values('I4',9)
insert into butacas (cod_butaca,id_sala)
values('I5',9)
insert into butacas (cod_butaca,id_sala)
values('I6',9)
insert into butacas (cod_butaca,id_sala)
values('I7',9)
insert into butacas (cod_butaca,id_sala)
values('I8',9)
insert into butacas (cod_butaca,id_sala)
values('I9',9)
insert into butacas (cod_butaca,id_sala)
values('I10',9)

insert into butacas (cod_butaca,id_sala)
values('J1',9)
insert into butacas (cod_butaca,id_sala)
values('J2',9)
insert into butacas (cod_butaca,id_sala)
values('J3',9)
insert into butacas (cod_butaca,id_sala)
values('J4',9)
insert into butacas (cod_butaca,id_sala)
values('J5',9)
insert into butacas (cod_butaca,id_sala)
values('J6',9)
insert into butacas (cod_butaca,id_sala)
values('J7',9)
insert into butacas (cod_butaca,id_sala)
values('J8',9)
insert into butacas (cod_butaca,id_sala)
values('J9',9)
insert into butacas (cod_butaca,id_sala)
values('J10',9)

insert into butacas (cod_butaca,id_sala)
values('A1',10)
insert into butacas (cod_butaca,id_sala)
values('A2',10)
insert into butacas (cod_butaca,id_sala)
values('A3',10)
insert into butacas (cod_butaca,id_sala)
values('A4',10)
insert into butacas (cod_butaca,id_sala)
values('A5',10)
insert into butacas (cod_butaca,id_sala)
values('A6',10)
insert into butacas (cod_butaca,id_sala)
values('A7',10)
insert into butacas (cod_butaca,id_sala)
values('A8',10)
insert into butacas (cod_butaca,id_sala)
values('A9',10)
insert into butacas (cod_butaca,id_sala)
values('A10',10)

insert into butacas (cod_butaca,id_sala)
values('B1',10)
insert into butacas (cod_butaca,id_sala)
values('B2',10)
insert into butacas (cod_butaca,id_sala)
values('B3',10)
insert into butacas (cod_butaca,id_sala)
values('B4',10)
insert into butacas (cod_butaca,id_sala)
values('B5',10)
insert into butacas (cod_butaca,id_sala)
values('B6',10)
insert into butacas (cod_butaca,id_sala)
values('B7',10)
insert into butacas (cod_butaca,id_sala)
values('B8',10)
insert into butacas (cod_butaca,id_sala)
values('B9',10)
insert into butacas (cod_butaca,id_sala)
values('B10',10)

insert into butacas (cod_butaca,id_sala)
values('C1',10)
insert into butacas (cod_butaca,id_sala)
values('C2',10)
insert into butacas (cod_butaca,id_sala)
values('C3',10)
insert into butacas (cod_butaca,id_sala)
values('C4',10)
insert into butacas (cod_butaca,id_sala)
values('C5',10)
insert into butacas (cod_butaca,id_sala)
values('C6',10)
insert into butacas (cod_butaca,id_sala)
values('C7',10)
insert into butacas (cod_butaca,id_sala)
values('C8',10)
insert into butacas (cod_butaca,id_sala)
values('C9',10)
insert into butacas (cod_butaca,id_sala)
values('C10',10)

insert into butacas (cod_butaca,id_sala)
values('D1',10)
insert into butacas (cod_butaca,id_sala)
values('D2',10)
insert into butacas (cod_butaca,id_sala)
values('D3',10)
insert into butacas (cod_butaca,id_sala)
values('D4',10)
insert into butacas (cod_butaca,id_sala)
values('D5',10)
insert into butacas (cod_butaca,id_sala)
values('D6',10)
insert into butacas (cod_butaca,id_sala)
values('D7',10)
insert into butacas (cod_butaca,id_sala)
values('D8',10)
insert into butacas (cod_butaca,id_sala)
values('D9',10)
insert into butacas (cod_butaca,id_sala)
values('D10',10)

insert into butacas (cod_butaca,id_sala)
values('E1',10)
insert into butacas (cod_butaca,id_sala)
values('E2',10)
insert into butacas (cod_butaca,id_sala)
values('E3',10)
insert into butacas (cod_butaca,id_sala)
values('E4',10)
insert into butacas (cod_butaca,id_sala)
values('E5',10)
insert into butacas (cod_butaca,id_sala)
values('E6',10)
insert into butacas (cod_butaca,id_sala)
values('E7',10)
insert into butacas (cod_butaca,id_sala)
values('E8',10)
insert into butacas (cod_butaca,id_sala)
values('E9',10)
insert into butacas (cod_butaca,id_sala)
values('E10',10)

insert into butacas (cod_butaca,id_sala)
values('F1',10)
insert into butacas (cod_butaca,id_sala)
values('F2',10)
insert into butacas (cod_butaca,id_sala)
values('F3',10)
insert into butacas (cod_butaca,id_sala)
values('F4',10)
insert into butacas (cod_butaca,id_sala)
values('F5',10)
insert into butacas (cod_butaca,id_sala)
values('F6',10)
insert into butacas (cod_butaca,id_sala)
values('F7',10)
insert into butacas (cod_butaca,id_sala)
values('F8',10)
insert into butacas (cod_butaca,id_sala)
values('F9',10)
insert into butacas (cod_butaca,id_sala)
values('F10',10)

insert into butacas (cod_butaca,id_sala)
values('G1',10)
insert into butacas (cod_butaca,id_sala)
values('G2',10)
insert into butacas (cod_butaca,id_sala)
values('G3',10)
insert into butacas (cod_butaca,id_sala)
values('G4',10)
insert into butacas (cod_butaca,id_sala)
values('G5',10)
insert into butacas (cod_butaca,id_sala)
values('G6',10)
insert into butacas (cod_butaca,id_sala)
values('G7',10)
insert into butacas (cod_butaca,id_sala)
values('G8',10)
insert into butacas (cod_butaca,id_sala)
values('G9',10)
insert into butacas (cod_butaca,id_sala)
values('G10',10)

insert into butacas (cod_butaca,id_sala)
values('H1',10)
insert into butacas (cod_butaca,id_sala)
values('H2',10)
insert into butacas (cod_butaca,id_sala)
values('H3',10)
insert into butacas (cod_butaca,id_sala)
values('H4',10)
insert into butacas (cod_butaca,id_sala)
values('H5',10)
insert into butacas (cod_butaca,id_sala)
values('H6',10)
insert into butacas (cod_butaca,id_sala)
values('H7',10)
insert into butacas (cod_butaca,id_sala)
values('H8',10)
insert into butacas (cod_butaca,id_sala)
values('H9',10)
insert into butacas (cod_butaca,id_sala)
values('H10',10)

insert into butacas (cod_butaca,id_sala)
values('I1',10)
insert into butacas (cod_butaca,id_sala)
values('I2',10)
insert into butacas (cod_butaca,id_sala)
values('I3',10)
insert into butacas (cod_butaca,id_sala)
values('I4',10)
insert into butacas (cod_butaca,id_sala)
values('I5',10)
insert into butacas (cod_butaca,id_sala)
values('I6',10)
insert into butacas (cod_butaca,id_sala)
values('I7',10)
insert into butacas (cod_butaca,id_sala)
values('I8',10)
insert into butacas (cod_butaca,id_sala)
values('I9',10)
insert into butacas (cod_butaca,id_sala)
values('I10',10)

insert into butacas (cod_butaca,id_sala)
values('J1',10)
insert into butacas (cod_butaca,id_sala)
values('J2',10)
insert into butacas (cod_butaca,id_sala)
values('J3',10)
insert into butacas (cod_butaca,id_sala)
values('J4',10)
insert into butacas (cod_butaca,id_sala)
values('J5',10)
insert into butacas (cod_butaca,id_sala)
values('J6',10)
insert into butacas (cod_butaca,id_sala)
values('J7',10)
insert into butacas (cod_butaca,id_sala)
values('J8',10)
insert into butacas (cod_butaca,id_sala)
values('J9',10)
insert into butacas (cod_butaca,id_sala)
values('J10',10)

insert into butacas (cod_butaca,id_sala)
values('A1',11)
insert into butacas (cod_butaca,id_sala)
values('A2',11)
insert into butacas (cod_butaca,id_sala)
values('A3',11)
insert into butacas (cod_butaca,id_sala)
values('A4',11)
insert into butacas (cod_butaca,id_sala)
values('A5',11)
insert into butacas (cod_butaca,id_sala)
values('A6',11)
insert into butacas (cod_butaca,id_sala)
values('A7',11)
insert into butacas (cod_butaca,id_sala)
values('A8',11)
insert into butacas (cod_butaca,id_sala)
values('A9',11)
insert into butacas (cod_butaca,id_sala)
values('A10',11)

insert into butacas (cod_butaca,id_sala)
values('B1',11)
insert into butacas (cod_butaca,id_sala)
values('B2',11)
insert into butacas (cod_butaca,id_sala)
values('B3',11)
insert into butacas (cod_butaca,id_sala)
values('B4',11)
insert into butacas (cod_butaca,id_sala)
values('B5',11)
insert into butacas (cod_butaca,id_sala)
values('B6',11)
insert into butacas (cod_butaca,id_sala)
values('B7',11)
insert into butacas (cod_butaca,id_sala)
values('B8',11)
insert into butacas (cod_butaca,id_sala)
values('B9',11)
insert into butacas (cod_butaca,id_sala)
values('B10',11)

insert into butacas (cod_butaca,id_sala)
values('C1',11)
insert into butacas (cod_butaca,id_sala)
values('C2',11)
insert into butacas (cod_butaca,id_sala)
values('C3',11)
insert into butacas (cod_butaca,id_sala)
values('C4',11)
insert into butacas (cod_butaca,id_sala)
values('C5',11)
insert into butacas (cod_butaca,id_sala)
values('C6',11)
insert into butacas (cod_butaca,id_sala)
values('C7',11)
insert into butacas (cod_butaca,id_sala)
values('C8',11)
insert into butacas (cod_butaca,id_sala)
values('C9',11)
insert into butacas (cod_butaca,id_sala)
values('C10',11)

insert into butacas (cod_butaca,id_sala)
values('D1',11)
insert into butacas (cod_butaca,id_sala)
values('D2',11)
insert into butacas (cod_butaca,id_sala)
values('D3',11)
insert into butacas (cod_butaca,id_sala)
values('D4',11)
insert into butacas (cod_butaca,id_sala)
values('D5',11)
insert into butacas (cod_butaca,id_sala)
values('D6',11)
insert into butacas (cod_butaca,id_sala)
values('D7',11)
insert into butacas (cod_butaca,id_sala)
values('D8',11)
insert into butacas (cod_butaca,id_sala)
values('D9',11)
insert into butacas (cod_butaca,id_sala)
values('D10',11)

insert into butacas (cod_butaca,id_sala)
values('E1',11)
insert into butacas (cod_butaca,id_sala)
values('E2',11)
insert into butacas (cod_butaca,id_sala)
values('E3',11)
insert into butacas (cod_butaca,id_sala)
values('E4',11)
insert into butacas (cod_butaca,id_sala)
values('E5',11)
insert into butacas (cod_butaca,id_sala)
values('E6',11)
insert into butacas (cod_butaca,id_sala)
values('E7',11)
insert into butacas (cod_butaca,id_sala)
values('E8',11)
insert into butacas (cod_butaca,id_sala)
values('E9',11)
insert into butacas (cod_butaca,id_sala)
values('E10',11)

insert into butacas (cod_butaca,id_sala)
values('F1',11)
insert into butacas (cod_butaca,id_sala)
values('F2',11)
insert into butacas (cod_butaca,id_sala)
values('F3',11)
insert into butacas (cod_butaca,id_sala)
values('F4',11)
insert into butacas (cod_butaca,id_sala)
values('F5',11)
insert into butacas (cod_butaca,id_sala)
values('F6',11)
insert into butacas (cod_butaca,id_sala)
values('F7',11)
insert into butacas (cod_butaca,id_sala)
values('F8',11)
insert into butacas (cod_butaca,id_sala)
values('F9',11)
insert into butacas (cod_butaca,id_sala)
values('F10',11)

insert into butacas (cod_butaca,id_sala)
values('G1',11)
insert into butacas (cod_butaca,id_sala)
values('G2',11)
insert into butacas (cod_butaca,id_sala)
values('G3',11)
insert into butacas (cod_butaca,id_sala)
values('G4',11)
insert into butacas (cod_butaca,id_sala)
values('G5',11)
insert into butacas (cod_butaca,id_sala)
values('G6',11)
insert into butacas (cod_butaca,id_sala)
values('G7',11)
insert into butacas (cod_butaca,id_sala)
values('G8',11)
insert into butacas (cod_butaca,id_sala)
values('G9',11)
insert into butacas (cod_butaca,id_sala)
values('G10',11)

insert into butacas (cod_butaca,id_sala)
values('H1',11)
insert into butacas (cod_butaca,id_sala)
values('H2',11)
insert into butacas (cod_butaca,id_sala)
values('H3',11)
insert into butacas (cod_butaca,id_sala)
values('H4',11)
insert into butacas (cod_butaca,id_sala)
values('H5',11)
insert into butacas (cod_butaca,id_sala)
values('H6',11)
insert into butacas (cod_butaca,id_sala)
values('H7',11)
insert into butacas (cod_butaca,id_sala)
values('H8',11)
insert into butacas (cod_butaca,id_sala)
values('H9',11)
insert into butacas (cod_butaca,id_sala)
values('H10',11)

insert into butacas (cod_butaca,id_sala)
values('I1',11)
insert into butacas (cod_butaca,id_sala)
values('I2',11)
insert into butacas (cod_butaca,id_sala)
values('I3',11)
insert into butacas (cod_butaca,id_sala)
values('I4',11)
insert into butacas (cod_butaca,id_sala)
values('I5',11)
insert into butacas (cod_butaca,id_sala)
values('I6',11)
insert into butacas (cod_butaca,id_sala)
values('I7',11)
insert into butacas (cod_butaca,id_sala)
values('I8',11)
insert into butacas (cod_butaca,id_sala)
values('I9',11)
insert into butacas (cod_butaca,id_sala)
values('I10',11)

insert into butacas (cod_butaca,id_sala)
values('J1',11)
insert into butacas (cod_butaca,id_sala)
values('J2',11)
insert into butacas (cod_butaca,id_sala)
values('J3',11)
insert into butacas (cod_butaca,id_sala)
values('J4',11)
insert into butacas (cod_butaca,id_sala)
values('J5',11)
insert into butacas (cod_butaca,id_sala)
values('J6',11)
insert into butacas (cod_butaca,id_sala)
values('J7',11)
insert into butacas (cod_butaca,id_sala)
values('J8',11)
insert into butacas (cod_butaca,id_sala)
values('J9',11)
insert into butacas (cod_butaca,id_sala)
values('J10',11)

insert into butacas (cod_butaca,id_sala)
values('A1',12)
insert into butacas (cod_butaca,id_sala)
values('A2',12)
insert into butacas (cod_butaca,id_sala)
values('A3',12)
insert into butacas (cod_butaca,id_sala)
values('A4',12)
insert into butacas (cod_butaca,id_sala)
values('A5',12)
insert into butacas (cod_butaca,id_sala)
values('A6',12)
insert into butacas (cod_butaca,id_sala)
values('A7',12)
insert into butacas (cod_butaca,id_sala)
values('A8',12)
insert into butacas (cod_butaca,id_sala)
values('A9',12)
insert into butacas (cod_butaca,id_sala)
values('A10',12)

insert into butacas (cod_butaca,id_sala)
values('B1',12)
insert into butacas (cod_butaca,id_sala)
values('B2',12)
insert into butacas (cod_butaca,id_sala)
values('B3',12)
insert into butacas (cod_butaca,id_sala)
values('B4',12)
insert into butacas (cod_butaca,id_sala)
values('B5',12)
insert into butacas (cod_butaca,id_sala)
values('B6',12)
insert into butacas (cod_butaca,id_sala)
values('B7',12)
insert into butacas (cod_butaca,id_sala)
values('B8',12)
insert into butacas (cod_butaca,id_sala)
values('B9',12)
insert into butacas (cod_butaca,id_sala)
values('B10',12)

insert into butacas (cod_butaca,id_sala)
values('C1',12)
insert into butacas (cod_butaca,id_sala)
values('C2',12)
insert into butacas (cod_butaca,id_sala)
values('C3',12)
insert into butacas (cod_butaca,id_sala)
values('C4',12)
insert into butacas (cod_butaca,id_sala)
values('C5',12)
insert into butacas (cod_butaca,id_sala)
values('C6',12)
insert into butacas (cod_butaca,id_sala)
values('C7',12)
insert into butacas (cod_butaca,id_sala)
values('C8',12)
insert into butacas (cod_butaca,id_sala)
values('C9',12)
insert into butacas (cod_butaca,id_sala)
values('C10',12)

insert into butacas (cod_butaca,id_sala)
values('D1',12)
insert into butacas (cod_butaca,id_sala)
values('D2',12)
insert into butacas (cod_butaca,id_sala)
values('D3',12)
insert into butacas (cod_butaca,id_sala)
values('D4',12)
insert into butacas (cod_butaca,id_sala)
values('D5',12)
insert into butacas (cod_butaca,id_sala)
values('D6',12)
insert into butacas (cod_butaca,id_sala)
values('D7',12)
insert into butacas (cod_butaca,id_sala)
values('D8',12)
insert into butacas (cod_butaca,id_sala)
values('D9',12)
insert into butacas (cod_butaca,id_sala)
values('D10',12)

insert into butacas (cod_butaca,id_sala)
values('E1',12)
insert into butacas (cod_butaca,id_sala)
values('E2',12)
insert into butacas (cod_butaca,id_sala)
values('E3',12)
insert into butacas (cod_butaca,id_sala)
values('E4',12)
insert into butacas (cod_butaca,id_sala)
values('E5',12)
insert into butacas (cod_butaca,id_sala)
values('E6',12)
insert into butacas (cod_butaca,id_sala)
values('E7',12)
insert into butacas (cod_butaca,id_sala)
values('E8',12)
insert into butacas (cod_butaca,id_sala)
values('E9',12)
insert into butacas (cod_butaca,id_sala)
values('E10',12)

insert into butacas (cod_butaca,id_sala)
values('F1',12)
insert into butacas (cod_butaca,id_sala)
values('F2',12)
insert into butacas (cod_butaca,id_sala)
values('F3',12)
insert into butacas (cod_butaca,id_sala)
values('F4',12)
insert into butacas (cod_butaca,id_sala)
values('F5',12)
insert into butacas (cod_butaca,id_sala)
values('F6',12)
insert into butacas (cod_butaca,id_sala)
values('F7',12)
insert into butacas (cod_butaca,id_sala)
values('F8',12)
insert into butacas (cod_butaca,id_sala)
values('F9',12)
insert into butacas (cod_butaca,id_sala)
values('F10',12)

insert into butacas (cod_butaca,id_sala)
values('G1',12)
insert into butacas (cod_butaca,id_sala)
values('G2',12)
insert into butacas (cod_butaca,id_sala)
values('G3',12)
insert into butacas (cod_butaca,id_sala)
values('G4',12)
insert into butacas (cod_butaca,id_sala)
values('G5',12)
insert into butacas (cod_butaca,id_sala)
values('G6',12)
insert into butacas (cod_butaca,id_sala)
values('G7',12)
insert into butacas (cod_butaca,id_sala)
values('G8',12)
insert into butacas (cod_butaca,id_sala)
values('G9',12)
insert into butacas (cod_butaca,id_sala)
values('G10',12)

insert into butacas (cod_butaca,id_sala)
values('H1',12)
insert into butacas (cod_butaca,id_sala)
values('H2',12)
insert into butacas (cod_butaca,id_sala)
values('H3',12)
insert into butacas (cod_butaca,id_sala)
values('H4',12)
insert into butacas (cod_butaca,id_sala)
values('H5',12)
insert into butacas (cod_butaca,id_sala)
values('H6',12)
insert into butacas (cod_butaca,id_sala)
values('H7',12)
insert into butacas (cod_butaca,id_sala)
values('H8',12)
insert into butacas (cod_butaca,id_sala)
values('H9',12)
insert into butacas (cod_butaca,id_sala)
values('H10',12)

insert into butacas (cod_butaca,id_sala)
values('I1',12)
insert into butacas (cod_butaca,id_sala)
values('I2',12)
insert into butacas (cod_butaca,id_sala)
values('I3',12)
insert into butacas (cod_butaca,id_sala)
values('I4',12)
insert into butacas (cod_butaca,id_sala)
values('I5',12)
insert into butacas (cod_butaca,id_sala)
values('I6',12)
insert into butacas (cod_butaca,id_sala)
values('I7',12)
insert into butacas (cod_butaca,id_sala)
values('I8',12)
insert into butacas (cod_butaca,id_sala)
values('I9',12)
insert into butacas (cod_butaca,id_sala)
values('I10',12)

insert into butacas (cod_butaca,id_sala)
values('J1',12)
insert into butacas (cod_butaca,id_sala)
values('J2',12)
insert into butacas (cod_butaca,id_sala)
values('J3',12)
insert into butacas (cod_butaca,id_sala)
values('J4',12)
insert into butacas (cod_butaca,id_sala)
values('J5',12)
insert into butacas (cod_butaca,id_sala)
values('J6',12)
insert into butacas (cod_butaca,id_sala)
values('J7',12)
insert into butacas (cod_butaca,id_sala)
values('J8',12)
insert into butacas (cod_butaca,id_sala)
values('J9',12)
insert into butacas (cod_butaca,id_sala)
values('J10',12)

insert into butacas (cod_butaca,id_sala)
values('A1',13)
insert into butacas (cod_butaca,id_sala)
values('A2',13)
insert into butacas (cod_butaca,id_sala)
values('A3',13)
insert into butacas (cod_butaca,id_sala)
values('A4',13)
insert into butacas (cod_butaca,id_sala)
values('A5',13)
insert into butacas (cod_butaca,id_sala)
values('A6',13)
insert into butacas (cod_butaca,id_sala)
values('A7',13)
insert into butacas (cod_butaca,id_sala)
values('A8',13)
insert into butacas (cod_butaca,id_sala)
values('A9',13)
insert into butacas (cod_butaca,id_sala)
values('A10',13)

insert into butacas (cod_butaca,id_sala)
values('B1',13)
insert into butacas (cod_butaca,id_sala)
values('B2',13)
insert into butacas (cod_butaca,id_sala)
values('B3',13)
insert into butacas (cod_butaca,id_sala)
values('B4',13)
insert into butacas (cod_butaca,id_sala)
values('B5',13)
insert into butacas (cod_butaca,id_sala)
values('B6',13)
insert into butacas (cod_butaca,id_sala)
values('B7',13)
insert into butacas (cod_butaca,id_sala)
values('B8',13)
insert into butacas (cod_butaca,id_sala)
values('B9',13)
insert into butacas (cod_butaca,id_sala)
values('B10',13)

insert into butacas (cod_butaca,id_sala)
values('C1',13)
insert into butacas (cod_butaca,id_sala)
values('C2',13)
insert into butacas (cod_butaca,id_sala)
values('C3',13)
insert into butacas (cod_butaca,id_sala)
values('C4',13)
insert into butacas (cod_butaca,id_sala)
values('C5',13)
insert into butacas (cod_butaca,id_sala)
values('C6',13)
insert into butacas (cod_butaca,id_sala)
values('C7',13)
insert into butacas (cod_butaca,id_sala)
values('C8',13)
insert into butacas (cod_butaca,id_sala)
values('C9',13)
insert into butacas (cod_butaca,id_sala)
values('C10',13)

insert into butacas (cod_butaca,id_sala)
values('D1',13)
insert into butacas (cod_butaca,id_sala)
values('D2',13)
insert into butacas (cod_butaca,id_sala)
values('D3',13)
insert into butacas (cod_butaca,id_sala)
values('D4',13)
insert into butacas (cod_butaca,id_sala)
values('D5',13)
insert into butacas (cod_butaca,id_sala)
values('D6',13)
insert into butacas (cod_butaca,id_sala)
values('D7',13)
insert into butacas (cod_butaca,id_sala)
values('D8',13)
insert into butacas (cod_butaca,id_sala)
values('D9',13)
insert into butacas (cod_butaca,id_sala)
values('D10',13)

insert into butacas (cod_butaca,id_sala)
values('E1',13)
insert into butacas (cod_butaca,id_sala)
values('E2',13)
insert into butacas (cod_butaca,id_sala)
values('E3',13)
insert into butacas (cod_butaca,id_sala)
values('E4',13)
insert into butacas (cod_butaca,id_sala)
values('E5',13)
insert into butacas (cod_butaca,id_sala)
values('E6',13)
insert into butacas (cod_butaca,id_sala)
values('E7',13)
insert into butacas (cod_butaca,id_sala)
values('E8',13)
insert into butacas (cod_butaca,id_sala)
values('E9',13)
insert into butacas (cod_butaca,id_sala)
values('E10',13)

insert into butacas (cod_butaca,id_sala)
values('F1',13)
insert into butacas (cod_butaca,id_sala)
values('F2',13)
insert into butacas (cod_butaca,id_sala)
values('F3',13)
insert into butacas (cod_butaca,id_sala)
values('F4',13)
insert into butacas (cod_butaca,id_sala)
values('F5',13)
insert into butacas (cod_butaca,id_sala)
values('F6',13)
insert into butacas (cod_butaca,id_sala)
values('F7',13)
insert into butacas (cod_butaca,id_sala)
values('F8',13)
insert into butacas (cod_butaca,id_sala)
values('F9',13)
insert into butacas (cod_butaca,id_sala)
values('F10',13)

insert into butacas (cod_butaca,id_sala)
values('G1',13)
insert into butacas (cod_butaca,id_sala)
values('G2',13)
insert into butacas (cod_butaca,id_sala)
values('G3',13)
insert into butacas (cod_butaca,id_sala)
values('G4',13)
insert into butacas (cod_butaca,id_sala)
values('G5',13)
insert into butacas (cod_butaca,id_sala)
values('G6',13)
insert into butacas (cod_butaca,id_sala)
values('G7',13)
insert into butacas (cod_butaca,id_sala)
values('G8',13)
insert into butacas (cod_butaca,id_sala)
values('G9',13)
insert into butacas (cod_butaca,id_sala)
values('G10',13)

insert into butacas (cod_butaca,id_sala)
values('H1',13)
insert into butacas (cod_butaca,id_sala)
values('H2',13)
insert into butacas (cod_butaca,id_sala)
values('H3',13)
insert into butacas (cod_butaca,id_sala)
values('H4',13)
insert into butacas (cod_butaca,id_sala)
values('H5',13)
insert into butacas (cod_butaca,id_sala)
values('H6',13)
insert into butacas (cod_butaca,id_sala)
values('H7',13)
insert into butacas (cod_butaca,id_sala)
values('H8',13)
insert into butacas (cod_butaca,id_sala)
values('H9',13)
insert into butacas (cod_butaca,id_sala)
values('H10',13)

insert into butacas (cod_butaca,id_sala)
values('I1',13)
insert into butacas (cod_butaca,id_sala)
values('I2',13)
insert into butacas (cod_butaca,id_sala)
values('I3',13)
insert into butacas (cod_butaca,id_sala)
values('I4',13)
insert into butacas (cod_butaca,id_sala)
values('I5',13)
insert into butacas (cod_butaca,id_sala)
values('I6',13)
insert into butacas (cod_butaca,id_sala)
values('I7',13)
insert into butacas (cod_butaca,id_sala)
values('I8',13)
insert into butacas (cod_butaca,id_sala)
values('I9',13)
insert into butacas (cod_butaca,id_sala)
values('I10',13)

insert into butacas (cod_butaca,id_sala)
values('J1',13)
insert into butacas (cod_butaca,id_sala)
values('J2',13)
insert into butacas (cod_butaca,id_sala)
values('J3',13)
insert into butacas (cod_butaca,id_sala)
values('J4',13)
insert into butacas (cod_butaca,id_sala)
values('J5',13)
insert into butacas (cod_butaca,id_sala)
values('J6',13)
insert into butacas (cod_butaca,id_sala)
values('J7',13)
insert into butacas (cod_butaca,id_sala)
values('J8',13)
insert into butacas (cod_butaca,id_sala)
values('J9',13)
insert into butacas (cod_butaca,id_sala)
values('J10',13)

insert into butacas (cod_butaca,id_sala)
values('A1',14)
insert into butacas (cod_butaca,id_sala)
values('A2',14)
insert into butacas (cod_butaca,id_sala)
values('A3',14)
insert into butacas (cod_butaca,id_sala)
values('A4',14)
insert into butacas (cod_butaca,id_sala)
values('A5',14)
insert into butacas (cod_butaca,id_sala)
values('A6',14)
insert into butacas (cod_butaca,id_sala)
values('A7',14)
insert into butacas (cod_butaca,id_sala)
values('A8',14)
insert into butacas (cod_butaca,id_sala)
values('A9',14)
insert into butacas (cod_butaca,id_sala)
values('A10',14)

insert into butacas (cod_butaca,id_sala)
values('B1',14)
insert into butacas (cod_butaca,id_sala)
values('B2',14)
insert into butacas (cod_butaca,id_sala)
values('B3',14)
insert into butacas (cod_butaca,id_sala)
values('B4',14)
insert into butacas (cod_butaca,id_sala)
values('B5',14)
insert into butacas (cod_butaca,id_sala)
values('B6',14)
insert into butacas (cod_butaca,id_sala)
values('B7',14)
insert into butacas (cod_butaca,id_sala)
values('B8',14)
insert into butacas (cod_butaca,id_sala)
values('B9',14)
insert into butacas (cod_butaca,id_sala)
values('B10',14)

insert into butacas (cod_butaca,id_sala)
values('C1',14)
insert into butacas (cod_butaca,id_sala)
values('C2',14)
insert into butacas (cod_butaca,id_sala)
values('C3',14)
insert into butacas (cod_butaca,id_sala)
values('C4',14)
insert into butacas (cod_butaca,id_sala)
values('C5',14)
insert into butacas (cod_butaca,id_sala)
values('C6',14)
insert into butacas (cod_butaca,id_sala)
values('C7',14)
insert into butacas (cod_butaca,id_sala)
values('C8',14)
insert into butacas (cod_butaca,id_sala)
values('C9',14)
insert into butacas (cod_butaca,id_sala)
values('C10',14)

insert into butacas (cod_butaca,id_sala)
values('D1',14)
insert into butacas (cod_butaca,id_sala)
values('D2',14)
insert into butacas (cod_butaca,id_sala)
values('D3',14)
insert into butacas (cod_butaca,id_sala)
values('D4',14)
insert into butacas (cod_butaca,id_sala)
values('D5',14)
insert into butacas (cod_butaca,id_sala)
values('D6',14)
insert into butacas (cod_butaca,id_sala)
values('D7',14)
insert into butacas (cod_butaca,id_sala)
values('D8',14)
insert into butacas (cod_butaca,id_sala)
values('D9',14)
insert into butacas (cod_butaca,id_sala)
values('D10',14)

insert into butacas (cod_butaca,id_sala)
values('E1',14)
insert into butacas (cod_butaca,id_sala)
values('E2',14)
insert into butacas (cod_butaca,id_sala)
values('E3',14)
insert into butacas (cod_butaca,id_sala)
values('E4',14)
insert into butacas (cod_butaca,id_sala)
values('E5',14)
insert into butacas (cod_butaca,id_sala)
values('E6',14)
insert into butacas (cod_butaca,id_sala)
values('E7',14)
insert into butacas (cod_butaca,id_sala)
values('E8',14)
insert into butacas (cod_butaca,id_sala)
values('E9',14)
insert into butacas (cod_butaca,id_sala)
values('E10',14)

insert into butacas (cod_butaca,id_sala)
values('F1',14)
insert into butacas (cod_butaca,id_sala)
values('F2',14)
insert into butacas (cod_butaca,id_sala)
values('F3',14)
insert into butacas (cod_butaca,id_sala)
values('F4',14)
insert into butacas (cod_butaca,id_sala)
values('F5',14)
insert into butacas (cod_butaca,id_sala)
values('F6',14)
insert into butacas (cod_butaca,id_sala)
values('F7',14)
insert into butacas (cod_butaca,id_sala)
values('F8',14)
insert into butacas (cod_butaca,id_sala)
values('F9',14)
insert into butacas (cod_butaca,id_sala)
values('F10',14)

insert into butacas (cod_butaca,id_sala)
values('G1',14)
insert into butacas (cod_butaca,id_sala)
values('G2',14)
insert into butacas (cod_butaca,id_sala)
values('G3',14)
insert into butacas (cod_butaca,id_sala)
values('G4',14)
insert into butacas (cod_butaca,id_sala)
values('G5',14)
insert into butacas (cod_butaca,id_sala)
values('G6',14)
insert into butacas (cod_butaca,id_sala)
values('G7',14)
insert into butacas (cod_butaca,id_sala)
values('G8',14)
insert into butacas (cod_butaca,id_sala)
values('G9',14)
insert into butacas (cod_butaca,id_sala)
values('G10',14)

insert into butacas (cod_butaca,id_sala)
values('H1',14)
insert into butacas (cod_butaca,id_sala)
values('H2',14)
insert into butacas (cod_butaca,id_sala)
values('H3',14)
insert into butacas (cod_butaca,id_sala)
values('H4',14)
insert into butacas (cod_butaca,id_sala)
values('H5',14)
insert into butacas (cod_butaca,id_sala)
values('H6',14)
insert into butacas (cod_butaca,id_sala)
values('H7',14)
insert into butacas (cod_butaca,id_sala)
values('H8',14)
insert into butacas (cod_butaca,id_sala)
values('H9',14)
insert into butacas (cod_butaca,id_sala)
values('H10',14)

insert into butacas (cod_butaca,id_sala)
values('I1',14)
insert into butacas (cod_butaca,id_sala)
values('I2',14)
insert into butacas (cod_butaca,id_sala)
values('I3',14)
insert into butacas (cod_butaca,id_sala)
values('I4',14)
insert into butacas (cod_butaca,id_sala)
values('I5',14)
insert into butacas (cod_butaca,id_sala)
values('I6',14)
insert into butacas (cod_butaca,id_sala)
values('I7',14)
insert into butacas (cod_butaca,id_sala)
values('I8',14)
insert into butacas (cod_butaca,id_sala)
values('I9',14)
insert into butacas (cod_butaca,id_sala)
values('I10',14)

insert into butacas (cod_butaca,id_sala)
values('J1',14)
insert into butacas (cod_butaca,id_sala)
values('J2',14)
insert into butacas (cod_butaca,id_sala)
values('J3',14)
insert into butacas (cod_butaca,id_sala)
values('J4',14)
insert into butacas (cod_butaca,id_sala)
values('J5',14)
insert into butacas (cod_butaca,id_sala)
values('J6',14)
insert into butacas (cod_butaca,id_sala)
values('J7',14)
insert into butacas (cod_butaca,id_sala)
values('J8',14)
insert into butacas (cod_butaca,id_sala)
values('J9',14)
insert into butacas (cod_butaca,id_sala)
values('J10',14)

insert into butacas (cod_butaca,id_sala)
values('A1',15)
insert into butacas (cod_butaca,id_sala)
values('A2',15)
insert into butacas (cod_butaca,id_sala)
values('A3',15)
insert into butacas (cod_butaca,id_sala)
values('A4',15)
insert into butacas (cod_butaca,id_sala)
values('A5',15)
insert into butacas (cod_butaca,id_sala)
values('A6',15)
insert into butacas (cod_butaca,id_sala)
values('A7',15)
insert into butacas (cod_butaca,id_sala)
values('A8',15)
insert into butacas (cod_butaca,id_sala)
values('A9',15)
insert into butacas (cod_butaca,id_sala)
values('A10',15)

insert into butacas (cod_butaca,id_sala)
values('B1',15)
insert into butacas (cod_butaca,id_sala)
values('B2',15)
insert into butacas (cod_butaca,id_sala)
values('B3',15)
insert into butacas (cod_butaca,id_sala)
values('B4',15)
insert into butacas (cod_butaca,id_sala)
values('B5',15)
insert into butacas (cod_butaca,id_sala)
values('B6',15)
insert into butacas (cod_butaca,id_sala)
values('B7',15)
insert into butacas (cod_butaca,id_sala)
values('B8',15)
insert into butacas (cod_butaca,id_sala)
values('B9',15)
insert into butacas (cod_butaca,id_sala)
values('B10',15)

insert into butacas (cod_butaca,id_sala)
values('C1',15)
insert into butacas (cod_butaca,id_sala)
values('C2',15)
insert into butacas (cod_butaca,id_sala)
values('C3',15)
insert into butacas (cod_butaca,id_sala)
values('C4',15)
insert into butacas (cod_butaca,id_sala)
values('C5',15)
insert into butacas (cod_butaca,id_sala)
values('C6',15)
insert into butacas (cod_butaca,id_sala)
values('C7',15)
insert into butacas (cod_butaca,id_sala)
values('C8',15)
insert into butacas (cod_butaca,id_sala)
values('C9',15)
insert into butacas (cod_butaca,id_sala)
values('C10',15)

insert into butacas (cod_butaca,id_sala)
values('D1',15)
insert into butacas (cod_butaca,id_sala)
values('D2',15)
insert into butacas (cod_butaca,id_sala)
values('D3',15)
insert into butacas (cod_butaca,id_sala)
values('D4',15)
insert into butacas (cod_butaca,id_sala)
values('D5',15)
insert into butacas (cod_butaca,id_sala)
values('D6',15)
insert into butacas (cod_butaca,id_sala)
values('D7',15)
insert into butacas (cod_butaca,id_sala)
values('D8',15)
insert into butacas (cod_butaca,id_sala)
values('D9',15)
insert into butacas (cod_butaca,id_sala)
values('D10',15)

insert into butacas (cod_butaca,id_sala)
values('E1',15)
insert into butacas (cod_butaca,id_sala)
values('E2',15)
insert into butacas (cod_butaca,id_sala)
values('E3',15)
insert into butacas (cod_butaca,id_sala)
values('E4',15)
insert into butacas (cod_butaca,id_sala)
values('E5',15)
insert into butacas (cod_butaca,id_sala)
values('E6',15)
insert into butacas (cod_butaca,id_sala)
values('E7',15)
insert into butacas (cod_butaca,id_sala)
values('E8',15)
insert into butacas (cod_butaca,id_sala)
values('E9',15)
insert into butacas (cod_butaca,id_sala)
values('E10',15)

insert into butacas (cod_butaca,id_sala)
values('F1',15)
insert into butacas (cod_butaca,id_sala)
values('F2',15)
insert into butacas (cod_butaca,id_sala)
values('F3',15)
insert into butacas (cod_butaca,id_sala)
values('F4',15)
insert into butacas (cod_butaca,id_sala)
values('F5',15)
insert into butacas (cod_butaca,id_sala)
values('F6',15)
insert into butacas (cod_butaca,id_sala)
values('F7',15)
insert into butacas (cod_butaca,id_sala)
values('F8',15)
insert into butacas (cod_butaca,id_sala)
values('F9',15)
insert into butacas (cod_butaca,id_sala)
values('F10',15)

insert into butacas (cod_butaca,id_sala)
values('G1',15)
insert into butacas (cod_butaca,id_sala)
values('G2',15)
insert into butacas (cod_butaca,id_sala)
values('G3',15)
insert into butacas (cod_butaca,id_sala)
values('G4',15)
insert into butacas (cod_butaca,id_sala)
values('G5',15)
insert into butacas (cod_butaca,id_sala)
values('G6',15)
insert into butacas (cod_butaca,id_sala)
values('G7',15)
insert into butacas (cod_butaca,id_sala)
values('G8',15)
insert into butacas (cod_butaca,id_sala)
values('G9',15)
insert into butacas (cod_butaca,id_sala)
values('G10',15)

insert into butacas (cod_butaca,id_sala)
values('H1',15)
insert into butacas (cod_butaca,id_sala)
values('H2',15)
insert into butacas (cod_butaca,id_sala)
values('H3',15)
insert into butacas (cod_butaca,id_sala)
values('H4',15)
insert into butacas (cod_butaca,id_sala)
values('H5',15)
insert into butacas (cod_butaca,id_sala)
values('H6',15)
insert into butacas (cod_butaca,id_sala)
values('H7',15)
insert into butacas (cod_butaca,id_sala)
values('H8',15)
insert into butacas (cod_butaca,id_sala)
values('H9',15)
insert into butacas (cod_butaca,id_sala)
values('H10',15)

insert into butacas (cod_butaca,id_sala)
values('I1',15)
insert into butacas (cod_butaca,id_sala)
values('I2',15)
insert into butacas (cod_butaca,id_sala)
values('I3',15)
insert into butacas (cod_butaca,id_sala)
values('I4',15)
insert into butacas (cod_butaca,id_sala)
values('I5',15)
insert into butacas (cod_butaca,id_sala)
values('I6',15)
insert into butacas (cod_butaca,id_sala)
values('I7',15)
insert into butacas (cod_butaca,id_sala)
values('I8',15)
insert into butacas (cod_butaca,id_sala)
values('I9',15)
insert into butacas (cod_butaca,id_sala)
values('I10',15)

insert into butacas (cod_butaca,id_sala)
values('J1',15)
insert into butacas (cod_butaca,id_sala)
values('J2',15)
insert into butacas (cod_butaca,id_sala)
values('J3',15)
insert into butacas (cod_butaca,id_sala)
values('J4',15)
insert into butacas (cod_butaca,id_sala)
values('J5',15)
insert into butacas (cod_butaca,id_sala)
values('J6',15)
insert into butacas (cod_butaca,id_sala)
values('J7',15)
insert into butacas (cod_butaca,id_sala)
values('J8',15)
insert into butacas (cod_butaca,id_sala)
values('J9',15)
insert into butacas (cod_butaca,id_sala)
values('J10',15)

insert into butacas (cod_butaca,id_sala)
values('A1',16)
insert into butacas (cod_butaca,id_sala)
values('A2',16)
insert into butacas (cod_butaca,id_sala)
values('A3',16)
insert into butacas (cod_butaca,id_sala)
values('A4',16)
insert into butacas (cod_butaca,id_sala)
values('A5',16)
insert into butacas (cod_butaca,id_sala)
values('A6',16)
insert into butacas (cod_butaca,id_sala)
values('A7',16)
insert into butacas (cod_butaca,id_sala)
values('A8',16)
insert into butacas (cod_butaca,id_sala)
values('A9',16)
insert into butacas (cod_butaca,id_sala)
values('A10',16)

insert into butacas (cod_butaca,id_sala)
values('B1',16)
insert into butacas (cod_butaca,id_sala)
values('B2',16)
insert into butacas (cod_butaca,id_sala)
values('B3',16)
insert into butacas (cod_butaca,id_sala)
values('B4',16)
insert into butacas (cod_butaca,id_sala)
values('B5',16)
insert into butacas (cod_butaca,id_sala)
values('B6',16)
insert into butacas (cod_butaca,id_sala)
values('B7',16)
insert into butacas (cod_butaca,id_sala)
values('B8',16)
insert into butacas (cod_butaca,id_sala)
values('B9',16)
insert into butacas (cod_butaca,id_sala)
values('B10',16)

insert into butacas (cod_butaca,id_sala)
values('C1',16)
insert into butacas (cod_butaca,id_sala)
values('C2',16)
insert into butacas (cod_butaca,id_sala)
values('C3',16)
insert into butacas (cod_butaca,id_sala)
values('C4',16)
insert into butacas (cod_butaca,id_sala)
values('C5',16)
insert into butacas (cod_butaca,id_sala)
values('C6',16)
insert into butacas (cod_butaca,id_sala)
values('C7',16)
insert into butacas (cod_butaca,id_sala)
values('C8',16)
insert into butacas (cod_butaca,id_sala)
values('C9',16)
insert into butacas (cod_butaca,id_sala)
values('C10',16)

insert into butacas (cod_butaca,id_sala)
values('D1',16)
insert into butacas (cod_butaca,id_sala)
values('D2',16)
insert into butacas (cod_butaca,id_sala)
values('D3',16)
insert into butacas (cod_butaca,id_sala)
values('D4',16)
insert into butacas (cod_butaca,id_sala)
values('D5',16)
insert into butacas (cod_butaca,id_sala)
values('D6',16)
insert into butacas (cod_butaca,id_sala)
values('D7',16)
insert into butacas (cod_butaca,id_sala)
values('D8',16)
insert into butacas (cod_butaca,id_sala)
values('D9',16)
insert into butacas (cod_butaca,id_sala)
values('D10',16)

insert into butacas (cod_butaca,id_sala)
values('E1',16)
insert into butacas (cod_butaca,id_sala)
values('E2',16)
insert into butacas (cod_butaca,id_sala)
values('E3',16)
insert into butacas (cod_butaca,id_sala)
values('E4',16)
insert into butacas (cod_butaca,id_sala)
values('E5',16)
insert into butacas (cod_butaca,id_sala)
values('E6',16)
insert into butacas (cod_butaca,id_sala)
values('E7',16)
insert into butacas (cod_butaca,id_sala)
values('E8',16)
insert into butacas (cod_butaca,id_sala)
values('E9',16)
insert into butacas (cod_butaca,id_sala)
values('E10',16)

insert into butacas (cod_butaca,id_sala)
values('F1',16)
insert into butacas (cod_butaca,id_sala)
values('F2',16)
insert into butacas (cod_butaca,id_sala)
values('F3',16)
insert into butacas (cod_butaca,id_sala)
values('F4',16)
insert into butacas (cod_butaca,id_sala)
values('F5',16)
insert into butacas (cod_butaca,id_sala)
values('F6',16)
insert into butacas (cod_butaca,id_sala)
values('F7',16)
insert into butacas (cod_butaca,id_sala)
values('F8',16)
insert into butacas (cod_butaca,id_sala)
values('F9',16)
insert into butacas (cod_butaca,id_sala)
values('F10',16)

insert into butacas (cod_butaca,id_sala)
values('G1',16)
insert into butacas (cod_butaca,id_sala)
values('G2',16)
insert into butacas (cod_butaca,id_sala)
values('G3',16)
insert into butacas (cod_butaca,id_sala)
values('G4',16)
insert into butacas (cod_butaca,id_sala)
values('G5',16)
insert into butacas (cod_butaca,id_sala)
values('G6',16)
insert into butacas (cod_butaca,id_sala)
values('G7',16)
insert into butacas (cod_butaca,id_sala)
values('G8',16)
insert into butacas (cod_butaca,id_sala)
values('G9',16)
insert into butacas (cod_butaca,id_sala)
values('G10',16)

insert into butacas (cod_butaca,id_sala)
values('H1',16)
insert into butacas (cod_butaca,id_sala)
values('H2',16)
insert into butacas (cod_butaca,id_sala)
values('H3',16)
insert into butacas (cod_butaca,id_sala)
values('H4',16)
insert into butacas (cod_butaca,id_sala)
values('H5',16)
insert into butacas (cod_butaca,id_sala)
values('H6',16)
insert into butacas (cod_butaca,id_sala)
values('H7',16)
insert into butacas (cod_butaca,id_sala)
values('H8',16)
insert into butacas (cod_butaca,id_sala)
values('H9',16)
insert into butacas (cod_butaca,id_sala)
values('H10',16)

insert into butacas (cod_butaca,id_sala)
values('I1',16)
insert into butacas (cod_butaca,id_sala)
values('I2',16)
insert into butacas (cod_butaca,id_sala)
values('I3',16)
insert into butacas (cod_butaca,id_sala)
values('I4',16)
insert into butacas (cod_butaca,id_sala)
values('I5',16)
insert into butacas (cod_butaca,id_sala)
values('I6',16)
insert into butacas (cod_butaca,id_sala)
values('I7',16)
insert into butacas (cod_butaca,id_sala)
values('I8',16)
insert into butacas (cod_butaca,id_sala)
values('I9',16)
insert into butacas (cod_butaca,id_sala)
values('I10',16)

insert into butacas (cod_butaca,id_sala)
values('J1',16)
insert into butacas (cod_butaca,id_sala)
values('J2',16)
insert into butacas (cod_butaca,id_sala)
values('J3',16)
insert into butacas (cod_butaca,id_sala)
values('J4',16)
insert into butacas (cod_butaca,id_sala)
values('J5',16)
insert into butacas (cod_butaca,id_sala)
values('J6',16)
insert into butacas (cod_butaca,id_sala)
values('J7',16)
insert into butacas (cod_butaca,id_sala)
values('J8',16)
insert into butacas (cod_butaca,id_sala)
values('J9',16)
insert into butacas (cod_butaca,id_sala)
values('J10',16)