use cine

insert into butacas (cod_butaca,id_sala)
values('A1',1)
insert into butacas (cod_butaca,id_sala)
values('A2',1)
insert into butacas (cod_butaca,id_sala)
values('A3',1)
insert into butacas (cod_butaca,id_sala)
values('A4',1)
insert into butacas (cod_butaca,id_sala)
values('A5',1)
insert into butacas (cod_butaca,id_sala)
values('A6',1)
insert into butacas (cod_butaca,id_sala)
values('A7',1)
insert into butacas (cod_butaca,id_sala)
values('A8',1)
insert into butacas (cod_butaca,id_sala)
values('A9',1)
insert into butacas (cod_butaca,id_sala)
values('A10',1)

insert into butacas (cod_butaca,id_sala)
values('B1',1)
insert into butacas (cod_butaca,id_sala)
values('B2',1)
insert into butacas (cod_butaca,id_sala)
values('B3',1)
insert into butacas (cod_butaca,id_sala)
values('B4',1)
insert into butacas (cod_butaca,id_sala)
values('B5',1)
insert into butacas (cod_butaca,id_sala)
values('B6',1)
insert into butacas (cod_butaca,id_sala)
values('B7',1)
insert into butacas (cod_butaca,id_sala)
values('B8',1)
insert into butacas (cod_butaca,id_sala)
values('B9',1)
insert into butacas (cod_butaca,id_sala)
values('B10',1)

insert into butacas (cod_butaca,id_sala)
values('C1',1)
insert into butacas (cod_butaca,id_sala)
values('C2',1)
insert into butacas (cod_butaca,id_sala)
values('C3',1)
insert into butacas (cod_butaca,id_sala)
values('C4',1)
insert into butacas (cod_butaca,id_sala)
values('C5',1)
insert into butacas (cod_butaca,id_sala)
values('C6',1)
insert into butacas (cod_butaca,id_sala)
values('C7',1)
insert into butacas (cod_butaca,id_sala)
values('C8',1)
insert into butacas (cod_butaca,id_sala)
values('C9',1)
insert into butacas (cod_butaca,id_sala)
values('C10',1)

insert into butacas (cod_butaca,id_sala)
values('D1',1)
insert into butacas (cod_butaca,id_sala)
values('D2',1)
insert into butacas (cod_butaca,id_sala)
values('D3',1)
insert into butacas (cod_butaca,id_sala)
values('D4',1)
insert into butacas (cod_butaca,id_sala)
values('D5',1)
insert into butacas (cod_butaca,id_sala)
values('D6',1)
insert into butacas (cod_butaca,id_sala)
values('D7',1)
insert into butacas (cod_butaca,id_sala)
values('D8',1)
insert into butacas (cod_butaca,id_sala)
values('D9',1)
insert into butacas (cod_butaca,id_sala)
values('D10',1)

insert into butacas (cod_butaca,id_sala)
values('E1',1)
insert into butacas (cod_butaca,id_sala)
values('E2',1)
insert into butacas (cod_butaca,id_sala)
values('E3',1)
insert into butacas (cod_butaca,id_sala)
values('E4',1)
insert into butacas (cod_butaca,id_sala)
values('E5',1)
insert into butacas (cod_butaca,id_sala)
values('E6',1)
insert into butacas (cod_butaca,id_sala)
values('E7',1)
insert into butacas (cod_butaca,id_sala)
values('E8',1)
insert into butacas (cod_butaca,id_sala)
values('E9',1)
insert into butacas (cod_butaca,id_sala)
values('E10',1)

insert into butacas (cod_butaca,id_sala)
values('F1',1)
insert into butacas (cod_butaca,id_sala)
values('F2',1)
insert into butacas (cod_butaca,id_sala)
values('F3',1)
insert into butacas (cod_butaca,id_sala)
values('F4',1)
insert into butacas (cod_butaca,id_sala)
values('F5',1)
insert into butacas (cod_butaca,id_sala)
values('F6',1)
insert into butacas (cod_butaca,id_sala)
values('F7',1)
insert into butacas (cod_butaca,id_sala)
values('F8',1)
insert into butacas (cod_butaca,id_sala)
values('F9',1)
insert into butacas (cod_butaca,id_sala)
values('F10',1)

insert into butacas (cod_butaca,id_sala)
values('G1',1)
insert into butacas (cod_butaca,id_sala)
values('G2',1)
insert into butacas (cod_butaca,id_sala)
values('G3',1)
insert into butacas (cod_butaca,id_sala)
values('G4',1)
insert into butacas (cod_butaca,id_sala)
values('G5',1)
insert into butacas (cod_butaca,id_sala)
values('G6',1)
insert into butacas (cod_butaca,id_sala)
values('G7',1)
insert into butacas (cod_butaca,id_sala)
values('G8',1)
insert into butacas (cod_butaca,id_sala)
values('G9',1)
insert into butacas (cod_butaca,id_sala)
values('G10',1)

insert into butacas (cod_butaca,id_sala)
values('H1',1)
insert into butacas (cod_butaca,id_sala)
values('H2',1)
insert into butacas (cod_butaca,id_sala)
values('H3',1)
insert into butacas (cod_butaca,id_sala)
values('H4',1)
insert into butacas (cod_butaca,id_sala)
values('H5',1)
insert into butacas (cod_butaca,id_sala)
values('H6',1)
insert into butacas (cod_butaca,id_sala)
values('H7',1)
insert into butacas (cod_butaca,id_sala)
values('H8',1)
insert into butacas (cod_butaca,id_sala)
values('H9',1)
insert into butacas (cod_butaca,id_sala)
values('H10',1)

insert into butacas (cod_butaca,id_sala)
values('I1',1)
insert into butacas (cod_butaca,id_sala)
values('I2',1)
insert into butacas (cod_butaca,id_sala)
values('I3',1)
insert into butacas (cod_butaca,id_sala)
values('I4',1)
insert into butacas (cod_butaca,id_sala)
values('I5',1)
insert into butacas (cod_butaca,id_sala)
values('I6',1)
insert into butacas (cod_butaca,id_sala)
values('I7',1)
insert into butacas (cod_butaca,id_sala)
values('I8',1)
insert into butacas (cod_butaca,id_sala)
values('I9',1)
insert into butacas (cod_butaca,id_sala)
values('I10',1)

insert into butacas (cod_butaca,id_sala)
values('J1',1)
insert into butacas (cod_butaca,id_sala)
values('J2',1)
insert into butacas (cod_butaca,id_sala)
values('J3',1)
insert into butacas (cod_butaca,id_sala)
values('J4',1)
insert into butacas (cod_butaca,id_sala)
values('J5',1)
insert into butacas (cod_butaca,id_sala)
values('J6',1)
insert into butacas (cod_butaca,id_sala)
values('J7',1)
insert into butacas (cod_butaca,id_sala)
values('J8',1)
insert into butacas (cod_butaca,id_sala)
values('J9',1)
insert into butacas (cod_butaca,id_sala)
values('J10',1)



insert into butacas (cod_butaca,id_sala)
values('A1',2)
insert into butacas (cod_butaca,id_sala)
values('A2',2)
insert into butacas (cod_butaca,id_sala)
values('A3',2)
insert into butacas (cod_butaca,id_sala)
values('A4',2)
insert into butacas (cod_butaca,id_sala)
values('A5',2)
insert into butacas (cod_butaca,id_sala)
values('A6',2)
insert into butacas (cod_butaca,id_sala)
values('A7',2)
insert into butacas (cod_butaca,id_sala)
values('A8',2)
insert into butacas (cod_butaca,id_sala)
values('A9',2)
insert into butacas (cod_butaca,id_sala)
values('A10',2)

insert into butacas (cod_butaca,id_sala)
values('B1',2)
insert into butacas (cod_butaca,id_sala)
values('B2',2)
insert into butacas (cod_butaca,id_sala)
values('B3',2)
insert into butacas (cod_butaca,id_sala)
values('B4',2)
insert into butacas (cod_butaca,id_sala)
values('B5',2)
insert into butacas (cod_butaca,id_sala)
values('B6',2)
insert into butacas (cod_butaca,id_sala)
values('B7',2)
insert into butacas (cod_butaca,id_sala)
values('B8',2)
insert into butacas (cod_butaca,id_sala)
values('B9',2)
insert into butacas (cod_butaca,id_sala)
values('B10',2)

insert into butacas (cod_butaca,id_sala)
values('C1',2)
insert into butacas (cod_butaca,id_sala)
values('C2',2)
insert into butacas (cod_butaca,id_sala)
values('C3',2)
insert into butacas (cod_butaca,id_sala)
values('C4',2)
insert into butacas (cod_butaca,id_sala)
values('C5',2)
insert into butacas (cod_butaca,id_sala)
values('C6',2)
insert into butacas (cod_butaca,id_sala)
values('C7',2)
insert into butacas (cod_butaca,id_sala)
values('C8',2)
insert into butacas (cod_butaca,id_sala)
values('C9',2)
insert into butacas (cod_butaca,id_sala)
values('C10',2)

insert into butacas (cod_butaca,id_sala)
values('D1',2)
insert into butacas (cod_butaca,id_sala)
values('D2',2)
insert into butacas (cod_butaca,id_sala)
values('D3',2)
insert into butacas (cod_butaca,id_sala)
values('D4',2)
insert into butacas (cod_butaca,id_sala)
values('D5',2)
insert into butacas (cod_butaca,id_sala)
values('D6',2)
insert into butacas (cod_butaca,id_sala)
values('D7',2)
insert into butacas (cod_butaca,id_sala)
values('D8',2)
insert into butacas (cod_butaca,id_sala)
values('D9',2)
insert into butacas (cod_butaca,id_sala)
values('D10',2)

insert into butacas (cod_butaca,id_sala)
values('E1',2)
insert into butacas (cod_butaca,id_sala)
values('E2',2)
insert into butacas (cod_butaca,id_sala)
values('E3',2)
insert into butacas (cod_butaca,id_sala)
values('E4',2)
insert into butacas (cod_butaca,id_sala)
values('E5',2)
insert into butacas (cod_butaca,id_sala)
values('E6',2)
insert into butacas (cod_butaca,id_sala)
values('E7',2)
insert into butacas (cod_butaca,id_sala)
values('E8',2)
insert into butacas (cod_butaca,id_sala)
values('E9',2)
insert into butacas (cod_butaca,id_sala)
values('E10',2)

insert into butacas (cod_butaca,id_sala)
values('F1',2)
insert into butacas (cod_butaca,id_sala)
values('F2',2)
insert into butacas (cod_butaca,id_sala)
values('F3',2)
insert into butacas (cod_butaca,id_sala)
values('F4',2)
insert into butacas (cod_butaca,id_sala)
values('F5',2)
insert into butacas (cod_butaca,id_sala)
values('F6',2)
insert into butacas (cod_butaca,id_sala)
values('F7',2)
insert into butacas (cod_butaca,id_sala)
values('F8',2)
insert into butacas (cod_butaca,id_sala)
values('F9',2)
insert into butacas (cod_butaca,id_sala)
values('F10',2)

insert into butacas (cod_butaca,id_sala)
values('G1',2)
insert into butacas (cod_butaca,id_sala)
values('G2',2)
insert into butacas (cod_butaca,id_sala)
values('G3',2)
insert into butacas (cod_butaca,id_sala)
values('G4',2)
insert into butacas (cod_butaca,id_sala)
values('G5',2)
insert into butacas (cod_butaca,id_sala)
values('G6',2)
insert into butacas (cod_butaca,id_sala)
values('G7',2)
insert into butacas (cod_butaca,id_sala)
values('G8',2)
insert into butacas (cod_butaca,id_sala)
values('G9',2)
insert into butacas (cod_butaca,id_sala)
values('G10',2)

insert into butacas (cod_butaca,id_sala)
values('H1',2)
insert into butacas (cod_butaca,id_sala)
values('H2',2)
insert into butacas (cod_butaca,id_sala)
values('H3',2)
insert into butacas (cod_butaca,id_sala)
values('H4',2)
insert into butacas (cod_butaca,id_sala)
values('H5',2)
insert into butacas (cod_butaca,id_sala)
values('H6',2)
insert into butacas (cod_butaca,id_sala)
values('H7',2)
insert into butacas (cod_butaca,id_sala)
values('H8',2)
insert into butacas (cod_butaca,id_sala)
values('H9',2)
insert into butacas (cod_butaca,id_sala)
values('H10',2)

insert into butacas (cod_butaca,id_sala)
values('I1',2)
insert into butacas (cod_butaca,id_sala)
values('I2',2)
insert into butacas (cod_butaca,id_sala)
values('I3',2)
insert into butacas (cod_butaca,id_sala)
values('I4',2)
insert into butacas (cod_butaca,id_sala)
values('I5',2)
insert into butacas (cod_butaca,id_sala)
values('I6',2)
insert into butacas (cod_butaca,id_sala)
values('I7',2)
insert into butacas (cod_butaca,id_sala)
values('I8',2)
insert into butacas (cod_butaca,id_sala)
values('I9',2)
insert into butacas (cod_butaca,id_sala)
values('I10',2)

insert into butacas (cod_butaca,id_sala)
values('J1',2)
insert into butacas (cod_butaca,id_sala)
values('J2',2)
insert into butacas (cod_butaca,id_sala)
values('J3',2)
insert into butacas (cod_butaca,id_sala)
values('J4',2)
insert into butacas (cod_butaca,id_sala)
values('J5',2)
insert into butacas (cod_butaca,id_sala)
values('J6',2)
insert into butacas (cod_butaca,id_sala)
values('J7',2)
insert into butacas (cod_butaca,id_sala)
values('J8',2)
insert into butacas (cod_butaca,id_sala)
values('J9',2)
insert into butacas (cod_butaca,id_sala)
values('J10',2)






insert into butacas (cod_butaca,id_sala)
values('A1',3)
insert into butacas (cod_butaca,id_sala)
values('A2',3)
insert into butacas (cod_butaca,id_sala)
values('A3',3)
insert into butacas (cod_butaca,id_sala)
values('A4',3)
insert into butacas (cod_butaca,id_sala)
values('A5',3)
insert into butacas (cod_butaca,id_sala)
values('A6',3)
insert into butacas (cod_butaca,id_sala)
values('A7',3)
insert into butacas (cod_butaca,id_sala)
values('A8',3)
insert into butacas (cod_butaca,id_sala)
values('A9',3)
insert into butacas (cod_butaca,id_sala)
values('A10',3)

insert into butacas (cod_butaca,id_sala)
values('B1',3)
insert into butacas (cod_butaca,id_sala)
values('B2',3)
insert into butacas (cod_butaca,id_sala)
values('B3',3)
insert into butacas (cod_butaca,id_sala)
values('B4',3)
insert into butacas (cod_butaca,id_sala)
values('B5',3)
insert into butacas (cod_butaca,id_sala)
values('B6',3)
insert into butacas (cod_butaca,id_sala)
values('B7',3)
insert into butacas (cod_butaca,id_sala)
values('B8',3)
insert into butacas (cod_butaca,id_sala)
values('B9',3)
insert into butacas (cod_butaca,id_sala)
values('B10',3)

insert into butacas (cod_butaca,id_sala)
values('C1',3)
insert into butacas (cod_butaca,id_sala)
values('C2',3)
insert into butacas (cod_butaca,id_sala)
values('C3',3)
insert into butacas (cod_butaca,id_sala)
values('C4',3)
insert into butacas (cod_butaca,id_sala)
values('C5',3)
insert into butacas (cod_butaca,id_sala)
values('C6',3)
insert into butacas (cod_butaca,id_sala)
values('C7',3)
insert into butacas (cod_butaca,id_sala)
values('C8',3)
insert into butacas (cod_butaca,id_sala)
values('C9',3)
insert into butacas (cod_butaca,id_sala)
values('C10',3)

insert into butacas (cod_butaca,id_sala)
values('D1',3)
insert into butacas (cod_butaca,id_sala)
values('D2',3)
insert into butacas (cod_butaca,id_sala)
values('D3',3)
insert into butacas (cod_butaca,id_sala)
values('D4',3)
insert into butacas (cod_butaca,id_sala)
values('D5',3)
insert into butacas (cod_butaca,id_sala)
values('D6',3)
insert into butacas (cod_butaca,id_sala)
values('D7',3)
insert into butacas (cod_butaca,id_sala)
values('D8',3)
insert into butacas (cod_butaca,id_sala)
values('D9',3)
insert into butacas (cod_butaca,id_sala)
values('D10',3)

insert into butacas (cod_butaca,id_sala)
values('E1',3)
insert into butacas (cod_butaca,id_sala)
values('E2',3)
insert into butacas (cod_butaca,id_sala)
values('E3',3)
insert into butacas (cod_butaca,id_sala)
values('E4',3)
insert into butacas (cod_butaca,id_sala)
values('E5',3)
insert into butacas (cod_butaca,id_sala)
values('E6',3)
insert into butacas (cod_butaca,id_sala)
values('E7',3)
insert into butacas (cod_butaca,id_sala)
values('E8',3)
insert into butacas (cod_butaca,id_sala)
values('E9',3)
insert into butacas (cod_butaca,id_sala)
values('E10',3)

insert into butacas (cod_butaca,id_sala)
values('F1',3)
insert into butacas (cod_butaca,id_sala)
values('F2',3)
insert into butacas (cod_butaca,id_sala)
values('F3',3)
insert into butacas (cod_butaca,id_sala)
values('F4',3)
insert into butacas (cod_butaca,id_sala)
values('F5',3)
insert into butacas (cod_butaca,id_sala)
values('F6',3)
insert into butacas (cod_butaca,id_sala)
values('F7',3)
insert into butacas (cod_butaca,id_sala)
values('F8',3)
insert into butacas (cod_butaca,id_sala)
values('F9',3)
insert into butacas (cod_butaca,id_sala)
values('F10',3)

insert into butacas (cod_butaca,id_sala)
values('G1',3)
insert into butacas (cod_butaca,id_sala)
values('G2',3)
insert into butacas (cod_butaca,id_sala)
values('G3',3)
insert into butacas (cod_butaca,id_sala)
values('G4',3)
insert into butacas (cod_butaca,id_sala)
values('G5',3)
insert into butacas (cod_butaca,id_sala)
values('G6',3)
insert into butacas (cod_butaca,id_sala)
values('G7',3)
insert into butacas (cod_butaca,id_sala)
values('G8',3)
insert into butacas (cod_butaca,id_sala)
values('G9',3)
insert into butacas (cod_butaca,id_sala)
values('G10',3)

insert into butacas (cod_butaca,id_sala)
values('H1',3)
insert into butacas (cod_butaca,id_sala)
values('H2',3)
insert into butacas (cod_butaca,id_sala)
values('H3',3)
insert into butacas (cod_butaca,id_sala)
values('H4',3)
insert into butacas (cod_butaca,id_sala)
values('H5',3)
insert into butacas (cod_butaca,id_sala)
values('H6',3)
insert into butacas (cod_butaca,id_sala)
values('H7',3)
insert into butacas (cod_butaca,id_sala)
values('H8',3)
insert into butacas (cod_butaca,id_sala)
values('H9',3)
insert into butacas (cod_butaca,id_sala)
values('H10',3)

insert into butacas (cod_butaca,id_sala)
values('I1',3)
insert into butacas (cod_butaca,id_sala)
values('I2',3)
insert into butacas (cod_butaca,id_sala)
values('I3',3)
insert into butacas (cod_butaca,id_sala)
values('I4',3)
insert into butacas (cod_butaca,id_sala)
values('I5',3)
insert into butacas (cod_butaca,id_sala)
values('I6',3)
insert into butacas (cod_butaca,id_sala)
values('I7',3)
insert into butacas (cod_butaca,id_sala)
values('I8',3)
insert into butacas (cod_butaca,id_sala)
values('I9',3)
insert into butacas (cod_butaca,id_sala)
values('I10',3)

insert into butacas (cod_butaca,id_sala)
values('J1',3)
insert into butacas (cod_butaca,id_sala)
values('J2',3)
insert into butacas (cod_butaca,id_sala)
values('J3',3)
insert into butacas (cod_butaca,id_sala)
values('J4',3)
insert into butacas (cod_butaca,id_sala)
values('J5',3)
insert into butacas (cod_butaca,id_sala)
values('J6',3)
insert into butacas (cod_butaca,id_sala)
values('J7',3)
insert into butacas (cod_butaca,id_sala)
values('J8',3)
insert into butacas (cod_butaca,id_sala)
values('J9',3)
insert into butacas (cod_butaca,id_sala)
values('J10',3)
