USE [cine]
GO
insert into promos_detalle(id_promocion,id_detalle)
values(1,49)
insert into promos_detalle(id_promocion,id_detalle)
values(2,50)
insert into promos_detalle(id_promocion,id_detalle)
values(3,51)
insert into promos_detalle(id_promocion,id_detalle)
values(4,52)
insert into promos_detalle(id_promocion,id_detalle)
values(1,53)
insert into promos_detalle(id_promocion,id_detalle)
values(2,54)
insert into promos_detalle(id_promocion,id_detalle)
values(1,55)
insert into promos_detalle(id_promocion,id_detalle)
values(3,56)
insert into promos_detalle(id_promocion,id_detalle)
values(4,57)
insert into promos_detalle(id_promocion,id_detalle)
values(2,58)
insert into promos_detalle(id_promocion,id_detalle)
values(3,59)
insert into promos_detalle(id_promocion,id_detalle)
values(2,48)
insert into promos_detalle(id_promocion,id_detalle)
values(2,40)
insert into promos_detalle(id_promocion,id_detalle)
values(3,41)
insert into promos_detalle(id_promocion,id_detalle)
values(4,42)
insert into promos_detalle(id_promocion,id_detalle)
values(1,43)
insert into promos_detalle(id_promocion,id_detalle)
values(2,35)
insert into promos_detalle(id_promocion,id_detalle)
values(4,36)
insert into promos_detalle(id_promocion,id_detalle)
values(1,37)
insert into promos_detalle(id_promocion,id_detalle)
values(2,38)
insert into promos_detalle(id_promocion,id_detalle)
values(3,39)